#ifndef L1TRC_TrcMod_DEF_H
#define L1TRC_TrcMod_DEF_H

	#include "L1Trc.h"

	#include "l1c_trace.h"
	#include "l1c2_trace.h"
	#include "l1i_cs_trace.h"
	#include "l1i_ps_trace.h"
	#include "l1sc_trace.h"
	#include "l1c_csd_trace.h"
	#include "L1D_Trace.h"
	#include "L1D2_Trace.h"
	#include "L1D_EDGE_Trace.h"
	#include "l1i_egprs_trace.h"
	#include "l1c_egprs_trace.h"
	#include "l1i_amr_trace.h"
	#include "l1t_amr_trace.h"
	#include "l1dm_trace.h"
	#include "UL1D_MLT_Trace1.h"
	#include "UL1D_MLT_Trace2.h"
	#include "UL1D_Trace.h"
	#include "UL1D_Trace1.h"
	#include "UL1D_Trace2.h"
	#include "UL1D_Trace3.h"
	#include "UL1D_Trace4.h"
	#include "UL1D_Trace5.h"
	#include "UL1D_Trace6.h"
	#include "UL1D_HSPA_Trace.h"
	#include "UL1D_HSPA_Trace1.h"
	#include "UL1D_HSPA_Trace2.h"
	#include "UL1D_PLUS_Trace1.h"
	#include "UL1C_Trace1.h"
	#include "UL1C_Trace2.h"
	#include "UL1C_Trace3.h"
	#include "UL1C_Trace4.h"
	#include "UL1TST_Trace1.h"
	#include "UL1SM_Trace1.h"
	#include "urlc_lisr_trace.h"
	#include "l1audio_trace.h"
	#include "L1D3_Trace.h"
	#include "L1_AFC_Trace.h"
	#include "l1c3_trace.h"
	#include "l1c4_trace.h"
	#include "l1c5_trace.h"
	#include "L1SM_Trace1.h"

#endif
