/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 *    pdn_def_mt6573_series.h
 *
 * Project:
 * --------
 *   Maui_Software
 *
 * Description:
 * ------------
 *   This file defines PDN X-MACRO for MT6573 series chips.
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

/*
 * Define pre-register PDN users. Need to sync with lpwr.c and register to L1SM.
 * format: X_PDN_USER(DEVICE_NAME, PDN_CON_REG, PDN_SET_REG, PDN_CLR_REG, PDN_REG_POS, PDN_OPTIONS)
 */

X_PDN_CONST(UART1, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_UART1, PDN_OPT_32BIT_REG | PDN_OPT_NEVER_OFF)
X_PDN_CONST(UART2, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_UART2, PDN_OPT_32BIT_REG | PDN_OPT_NEVER_OFF)
X_PDN_CONST(UART3, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_UART3, PDN_OPT_32BIT_REG | PDN_OPT_NEVER_OFF)
//X_PDN_USER(ALTER, 0, 0, 0, 0, 0)
X_PDN_CONST(GCU, MD2GSYS_CG_CON1, MD2GSYS_CG_SET1, MD2GSYS_CG_CLR1, MD2GSYS_CG_CON1_GCU, PDN_OPT_16BIT_REG)
X_PDN_CONST(DMA, DRVPDN_CON0, DRVPDN_CON1_SET, DRVPDN_CON1_CLR, DRVPDN_CON0_MDDMA, PDN_OPT_32BIT_REG)
X_PDN_CONST(SIM, AP_DRVPDN_CON1, AP_DRVPDN_CON1_SET, AP_DRVPDN_CON1_CLR, AP_DRVPDN_CON1_SIMIF0, PDN_OPT_32BIT_REG)
X_PDN_CONST(SIM2, AP_DRVPDN_CON1, AP_DRVPDN_CON1_SET, AP_DRVPDN_CON1_CLR, AP_DRVPDN_CON1_SIMIF1, PDN_OPT_32BIT_REG)
//X_PDN_USER(ADC, DRVPDN_CON1, DRVPDN_CON1_SET, DRVPDN_CON1_CLR, DRVPDN_CON1_ADC, PDN_OPT_16BIT_REG)
X_PDN_CONST(ADC, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_AUXADC2G, PDN_OPT_32BIT_REG)
//X_PDN_USER(B2SPI, 0, 0, 0, 0, 0)
//X_PDN_USER(GPT, 0, 0, 0, 0, 0)
X_PDN_CONST(PWM, AP_DRVPDN_CON1, AP_DRVPDN_CON1_SET, AP_DRVPDN_CON1_CLR, AP_DRVPDN_CON1_PWM, PDN_OPT_32BIT_REG)
//X_PDN_USER(PWM2, 0, 0, 0, 0, 0)
X_PDN_CONST(USB, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_USB, PDN_OPT_32BIT_REG)
X_PDN_CONST(MSDC, AP_DRVPDN_CON1, AP_DRVPDN_CON1_SET, AP_DRVPDN_CON1_CLR, AP_DRVPDN_CON0_MSDC, PDN_OPT_32BIT_REG)
X_PDN_CONST(MSDC2, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_MSDC2, PDN_OPT_32BIT_REG)
X_PDN_CONST(NFI, AP_DRVPDN_CON1, AP_DRVPDN_CON1_SET, AP_DRVPDN_CON1_CLR, AP_DRVPDN_CON1_NFI, PDN_OPT_32BIT_REG)
X_PDN_CONST(IRDA, AP_DRVPDN_CON1, AP_DRVPDN_CON1_SET, AP_DRVPDN_CON1_CLR, AP_DRVPDN_CON1_IRDAFRAMER, PDN_OPT_32BIT_REG)
//X_PDN_USER(TRC, 0, 0, 0, 0, 0)
//X_PDN_USER(IMGDMA, 0, 0, 0, 0, 0)
//X_PDN_USER(RESZ, 0, 0, 0, 0, 0)
X_PDN_CONST(GIF, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_GIF, PDN_OPT_32BIT_REG)
X_PDN_CONST(PNG, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_PNG, PDN_OPT_32BIT_REG)

/*
 * Define remaining PDN users.
 * format: X_PDN_CONST(DEVICE_NAME, PDN_CON_REG, PDN_SET_REG, PDN_CLR_REG, PDN_REG_POS, PDN_OPTIONS)
 */

X_PDN_CONST(DIVIDER, DRVPDN_CON0, DRVPDN_CON1_SET, DRVPDN_CON1_CLR, DRVPDN_CON0_DIVIDER, PDN_OPT_32BIT_REG)
X_PDN_CONST(OSTIMERMDARM, DRVPDN_CON0, DRVPDN_CON1_SET, DRVPDN_CON1_CLR, DRVPDN_CON0_OSTIMERMDARM, PDN_OPT_32BIT_REG)
X_PDN_CONST(OSTIMERFCORE4, DRVPDN_CON0, DRVPDN_CON1_SET, DRVPDN_CON1_CLR, DRVPDN_CON0_OSTIMERFCORE4, PDN_OPT_32BIT_REG)
X_PDN_CONST(AFC2G, DRVPDN_CON0, DRVPDN_CON1_SET, DRVPDN_CON1_CLR, DRVPDN_CON0_AFC2G, PDN_OPT_32BIT_REG)
X_PDN_CONST(BPI2G, DRVPDN_CON0, DRVPDN_CON1_SET, DRVPDN_CON1_CLR, DRVPDN_CON0_BPI2G, PDN_OPT_32BIT_REG)
X_PDN_CONST(DSI2G, DRVPDN_CON0, DRVPDN_CON1_SET, DRVPDN_CON1_CLR, DRVPDN_CON0_BSI2G, PDN_OPT_32BIT_REG)
X_PDN_CONST(TDMA, DRVPDN_CON0, DRVPDN_CON1_SET, DRVPDN_CON1_CLR, DRVPDN_CON0_TDMA, PDN_OPT_32BIT_REG)
X_PDN_CONST(WCDMATIMER, DRVPDN_CON0, DRVPDN_CON1_SET, DRVPDN_CON1_CLR, DRVPDN_CON0_WCDMATIMER, PDN_OPT_32BIT_REG)
X_PDN_CONST(PFC, DRVPDN_CON0, DRVPDN_CON1_SET, DRVPDN_CON1_CLR, DRVPDN_CON0_PFC, PDN_OPT_32BIT_REG)
X_PDN_CONST(LOGACC, DRVPDN_CON0, DRVPDN_CON1_SET, DRVPDN_CON1_CLR, DRVPDN_CON0_LOGACC, PDN_OPT_32BIT_REG)
X_PDN_CONST(AFC3G, DRVPDN_CON0, DRVPDN_CON1_SET, DRVPDN_CON1_CLR, DRVPDN_CON0_AFC3G, PDN_OPT_32BIT_REG)
X_PDN_CONST(BPI3G, DRVPDN_CON0, DRVPDN_CON1_SET, DRVPDN_CON1_CLR, DRVPDN_CON0_BPI3G, PDN_OPT_32BIT_REG)
X_PDN_CONST(BSI3G, DRVPDN_CON0, DRVPDN_CON1_SET, DRVPDN_CON1_CLR, DRVPDN_CON0_BSI3G, PDN_OPT_32BIT_REG)
X_PDN_CONST(MDIF, DRVPDN_CON0, DRVPDN_CON1_SET, DRVPDN_CON1_CLR, DRVPDN_CON0_MDIF, PDN_OPT_32BIT_REG)

X_PDN_CONST(UART4, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_UART4, PDN_OPT_32BIT_REG | PDN_OPT_NEVER_OFF)
X_PDN_CONST(APDMA, AP_DRVPDN_CON1, AP_DRVPDN_CON1_SET, AP_DRVPDN_CON1_CLR, AP_DRVPDN_CON1_APDMA, PDN_OPT_32BIT_REG)
X_PDN_CONST(MSDC3, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_MSDC3, PDN_OPT_32BIT_REG)
X_PDN_CONST(MSDC4, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_MSDC4, PDN_OPT_32BIT_REG)
X_PDN_CONST(USB2, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_USB11, PDN_OPT_32BIT_REG)
X_PDN_CONST(ADC2, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_AUXADC3G, PDN_OPT_32BIT_REG)

X_PDN_CONST(AFC2GPRE, DRVPDN_CON0, DRVPDN_CON0_SET, DRVPDN_CON0_CLR, DRVPDN_CON1_AFC2GPRE, PDN_OPT_32BIT_REG)
X_PDN_CONST(BPI2GPRE, DRVPDN_CON0, DRVPDN_CON0_SET, DRVPDN_CON0_CLR, DRVPDN_CON1_BPI2GPRE, PDN_OPT_32BIT_REG)
X_PDN_CONST(DSI2GPRE, DRVPDN_CON0, DRVPDN_CON0_SET, DRVPDN_CON0_CLR, DRVPDN_CON1_BSI2GPRE, PDN_OPT_32BIT_REG)

X_PDN_CONST(TP, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_TP, PDN_OPT_32BIT_REG)
X_PDN_CONST(2GTX, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_2GTX, PDN_OPT_32BIT_REG)

X_PDN_CONST(OSTIMERAPARM, AP_DRVPDN_CON1, AP_DRVPDN_CON1_SET, AP_DRVPDN_CON1_CLR, AP_DRVPDN_CON1_OSTIMERAPARM, PDN_OPT_32BIT_REG)
X_PDN_CONST(MIXEDSYS, AP_DRVPDN_CON1, AP_DRVPDN_CON1_SET, AP_DRVPDN_CON1_CLR, AP_DRVPDN_CON1_MIXEDSYS, PDN_OPT_32BIT_REG)
X_PDN_CONST(I2C, AP_DRVPDN_CON1, AP_DRVPDN_CON1_SET, AP_DRVPDN_CON1_CLR, AP_DRVPDN_CON1_I2C, PDN_OPT_32BIT_REG)
X_PDN_CONST(I2C2, AP_DRVPDN_CON1, AP_DRVPDN_CON1_SET, AP_DRVPDN_CON1_CLR, AP_DRVPDN_CON1_I2C2, PDN_OPT_32BIT_REG)
X_PDN_CONST(SEJ, AP_DRVPDN_CON1, AP_DRVPDN_CON1_SET, AP_DRVPDN_CON1_CLR, AP_DRVPDN_CON1_SEJ, PDN_OPT_32BIT_REG)
X_PDN_CONST(HDQONEWIRE, AP_DRVPDN_CON1, AP_DRVPDN_CON1_SET, AP_DRVPDN_CON1_CLR, AP_DRVPDN_CON1_HDQONEWIRE, PDN_OPT_32BIT_REG)
X_PDN_CONST(TRNG, AP_DRVPDN_CON1, AP_DRVPDN_CON1_SET, AP_DRVPDN_CON1_CLR, AP_DRVPDN_CON1_TRNG, PDN_OPT_32BIT_REG)

X_PDN_CONST(EQ, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_EQ, PDN_OPT_16BIT_REG)
X_PDN_CONST(PREEQ, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_PREEQ, PDN_OPT_16BIT_REG)
X_PDN_CONST(SEQRX, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_SEQRX, PDN_OPT_16BIT_REG)
X_PDN_CONST(SEQTX, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_SEQTX, PDN_OPT_16BIT_REG)
X_PDN_CONST(CONV, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_CONV, PDN_OPT_16BIT_REG)
X_PDN_CONST(FIRE, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_FIRE, PDN_OPT_16BIT_REG)
X_PDN_CONST(CRC, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_CRC, PDN_OPT_16BIT_REG)
X_PDN_CONST(ECRCE, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_ECRCE, PDN_OPT_16BIT_REG)
X_PDN_CONST(ECRCD, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_ECRCD, PDN_OPT_16BIT_REG)
X_PDN_CONST(ECONV, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_ECONV, PDN_OPT_16BIT_REG)
X_PDN_CONST(PUNC, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_PUNC, PDN_OPT_16BIT_REG)
X_PDN_CONST(VITERBI, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_VITERBI, PDN_OPT_16BIT_REG)
X_PDN_CONST(EAPG, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_EAPG, PDN_OPT_16BIT_REG)
X_PDN_CONST(ADDRGEN, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_ADDRGEN, PDN_OPT_16BIT_REG)
X_PDN_CONST(LOG2G, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_LOG2G, PDN_OPT_16BIT_REG)
X_PDN_CONST(DEINTDMA, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_DEINTDMA, PDN_OPT_16BIT_REG)

X_PDN_CONST(IRDMA, MD2GSYS_CG_CON1, MD2GSYS_CG_SET1, MD2GSYS_CG_CLR1, MD2GSYS_CG_CON1_IRDMA, PDN_OPT_16BIT_REG)
X_PDN_CONST(APCPRE, MD2GSYS_CG_CON1, MD2GSYS_CG_SET1, MD2GSYS_CG_CLR1, MD2GSYS_CG_CON1_APCPRE, PDN_OPT_16BIT_REG)
X_PDN_CONST(FCS, MD2GSYS_CG_CON1, MD2GSYS_CG_SET1, MD2GSYS_CG_CLR1, MD2GSYS_CG_CON1_FCS, PDN_OPT_16BIT_REG)
X_PDN_CONST(BFE, MD2GSYS_CG_CON1, MD2GSYS_CG_SET1, MD2GSYS_CG_CLR1, MD2GSYS_CG_CON1_BFE, PDN_OPT_16BIT_REG)
X_PDN_CONST(GCCTX, MD2GSYS_CG_CON1, MD2GSYS_CG_SET1, MD2GSYS_CG_CLR1, MD2GSYS_CG_CON1_GCCTX, PDN_OPT_16BIT_REG)
X_PDN_CONST(GCCRX, MD2GSYS_CG_CON1, MD2GSYS_CG_SET1, MD2GSYS_CG_CLR1, MD2GSYS_CG_CON1_GCCRX, PDN_OPT_16BIT_REG)

X_PDN_CONST(APC, MD2GSYS_CG_CON2, MD2GSYS_CG_SET2, MD2GSYS_CG_CLR2, MD2GSYS_CG_CON2_APC, PDN_OPT_16BIT_REG)

X_PDN_CONST(GMC1, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_GMC1, PDN_OPT_32BIT_REG)
X_PDN_CONST(G2D, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_G2D, PDN_OPT_32BIT_REG)
X_PDN_CONST(GCMQ, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_GCMQ, PDN_OPT_32BIT_REG)
X_PDN_CONST(JPGENC, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_JPGENC, PDN_OPT_32BIT_REG)
X_PDN_CONST(IDPMOUT0, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_IDPMOUT0, PDN_OPT_32BIT_REG)
X_PDN_CONST(JPGDEC, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_JPGDEC, PDN_OPT_32BIT_REG)
X_PDN_CONST(JPEGDMA, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_JPEGDMA, PDN_OPT_32BIT_REG)
X_PDN_CONST(IDPMOUT1, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_IDPMOUT1, PDN_OPT_32BIT_REG)
X_PDN_CONST(OVL, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_OVL, PDN_OPT_32BIT_REG)
X_PDN_CONST(ROTDMA2, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_ROTDMA2, PDN_OPT_32BIT_REG)
X_PDN_CONST(ISP, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_ISP, PDN_OPT_32BIT_REG)
X_PDN_CONST(IPP, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_IPP, PDN_OPT_32BIT_REG)
X_PDN_CONST(PRZ, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_PRZ, PDN_OPT_32BIT_REG)
X_PDN_CONST(CRZ, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_CRZ, PDN_OPT_32BIT_REG)
X_PDN_CONST(VRZ, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_VRZ, PDN_OPT_32BIT_REG)
X_PDN_CONST(EIS, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_EIS, PDN_OPT_32BIT_REG)
X_PDN_CONST(RDMA, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_RDMA, PDN_OPT_32BIT_REG)
X_PDN_CONST(RDMA1, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_RDMA1, PDN_OPT_32BIT_REG)
X_PDN_CONST(ROTDMA0, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_ROTDMA0, PDN_OPT_32BIT_REG)
X_PDN_CONST(ROTDMA1, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_ROTDMA1, PDN_OPT_32BIT_REG)
X_PDN_CONST(RESZLB, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_RESZLB, PDN_OPT_32BIT_REG)
X_PDN_CONST(LCD, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_LCD, PDN_OPT_32BIT_REG)
X_PDN_CONST(DPI, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_DPI, PDN_OPT_32BIT_REG)
X_PDN_CONST(CSI2, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_CSI2, PDN_OPT_32BIT_REG)
X_PDN_CONST(OVLBPS, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_OVLBPS, PDN_OPT_32BIT_REG)
X_PDN_CONST(FDVT, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_FDVT, PDN_OPT_32BIT_REG)
X_PDN_CONST(DSI, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_DSI, PDN_OPT_32BIT_REG)
X_PDN_CONST(RDMA1BPS, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_RDMA1BPS, PDN_OPT_32BIT_REG)
X_PDN_CONST(MMLMU, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_MMLMU, PDN_OPT_32BIT_REG)
X_PDN_CONST(BRZ, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_BRZ, PDN_OPT_32BIT_REG)

X_PDN_CONST(PRZ1, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_PRZ1, PDN_OPT_32BIT_REG)
X_PDN_CONST(ROTDMA3, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_ROTDMA3, PDN_OPT_32BIT_REG)
X_PDN_CONST(IDPMOUT2, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_IDPMOUT2, PDN_OPT_32BIT_REG)
X_PDN_CONST(IDPMOUT3, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_IDPMOUT3, PDN_OPT_32BIT_REG)
X_PDN_CONST(TVC, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_TVC, PDN_OPT_32BIT_REG)
X_PDN_CONST(TVE, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_TVE, PDN_OPT_32BIT_REG)
X_PDN_CONST(TVROT, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_TVROT, PDN_OPT_32BIT_REG)
X_PDN_CONST(HIF, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_HIF, PDN_OPT_32BIT_REG)
X_PDN_CONST(GMC1E, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_GMC1E, PDN_OPT_32BIT_REG)
X_PDN_CONST(GMC1SLV, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_GMC1SLV, PDN_OPT_32BIT_REG)

X_PDN_CONST(GMC2, MMSYS2_CG_CON0, MMSYS2_CG_SET0, MMSYS2_CG_CLR0, MMSYS2_CG_CON0_GMC2, PDN_OPT_32BIT_REG)
X_PDN_CONST(MFV, MMSYS2_CG_CON0, MMSYS2_CG_SET0, MMSYS2_CG_CLR0, MMSYS2_CG_CON0_MFV, PDN_OPT_32BIT_REG)
X_PDN_CONST(MFGCORE, MMSYS2_CG_CON0, MMSYS2_CG_SET0, MMSYS2_CG_CLR0, MMSYS2_CG_CON0_MFGCORE, PDN_OPT_32BIT_REG)
X_PDN_CONST(MFGMEM, MMSYS2_CG_CON0, MMSYS2_CG_SET0, MMSYS2_CG_CLR0, MMSYS2_CG_CON0_MFGMEM, PDN_OPT_32BIT_REG)
X_PDN_CONST(MFGSYS, MMSYS2_CG_CON0, MMSYS2_CG_SET0, MMSYS2_CG_CLR0, MMSYS2_CG_CON0_MFGSYS, PDN_OPT_32BIT_REG)
X_PDN_CONST(SPI, MMSYS2_CG_CON0, MMSYS2_CG_SET0, MMSYS2_CG_CLR0, MMSYS2_CG_CON0_SPI, PDN_OPT_32BIT_REG)
X_PDN_CONST(GMC2E, MMSYS2_CG_CON0, MMSYS2_CG_SET0, MMSYS2_CG_CLR0, MMSYS2_CG_CON0_GMC2E, PDN_OPT_32BIT_REG)



