/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 *    pdn_def_mt6589_series.h
 *
 * Project:
 * --------
 *   Maui_Software
 *
 * Description:
 * ------------
 *   This file defines PDN X-MACRO for MT6589 series chips.
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
  *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/
/** there 2 kind of PDN definition macro:
 *	X_PDN_USER: Define pre-register PDN users, that need to sync with lpwr.c and register to L1SM
 *	X_PDN_CONST: remaining PDN users.
 **/	



/*
 * Define pre-register PDN users. Need to sync with lpwr.c and register to L1SM.
 * format: X_PDN_USER(DEVICE_NAME, PDN_CON_REG, PDN_SET_REG, PDN_CLR_REG, PDN_REG_POS, PDN_OPTIONS)
 */

X_PDN_CONST(UART1, DRVPDN_MD_PWR_GLOBAL_CON0, DRVPDN_MD_PWR_GLOBAL_SET0, DRVPDN_MD_PWR_GLOBAL_CLR0, MD_PWR_GLOBAL_CON0_UART, PDN_OPT_32BIT_REG | PDN_OPT_NEVER_OFF)
/* use AP UART as UART2 and UART3 for DVT purpose */
//X_PDN_USER(UART2, DRVPDN_AP_CG_CON0, DRVPDN_AP_CG_SET0, DRVPDN_AP_CG_CLR0, AP_CG_CON0_AP_UART1, PDN_OPT_32BIT_REG)
//X_PDN_USER(UART3, DRVPDN_AP_CG_CON0, DRVPDN_AP_CG_SET0, DRVPDN_AP_CG_CLR0, AP_CG_CON0_AP_UART2, PDN_OPT_32BIT_REG)
//X_PDN_USER(ALTER, 0, 0, 0, 0, 0)
X_PDN_CONST(GCU, DRVPDN_MODEM_CG_CON2, DRVPDN_MODEM_CG_SET2, DRVPDN_MODEM_CG_CLR2, MODEM_CG_CON2_GCU, PDN_OPT_32BIT_REG)
X_PDN_CONST(DMA, DRVPDN_MD_PWR_GLOBAL_CON0, DRVPDN_MD_PWR_GLOBAL_SET0, DRVPDN_MD_PWR_GLOBAL_CLR0, MD_PWR_GLOBAL_CON0_DMA, PDN_OPT_32BIT_REG)
X_PDN_CONST(SIM, DRVPDN_MD_PWR_GLOBAL_CON0, DRVPDN_MD_PWR_GLOBAL_SET0, DRVPDN_MD_PWR_GLOBAL_CLR0, MD_PWR_GLOBAL_CON0_SIM1, PDN_OPT_32BIT_REG)
X_PDN_CONST(SIM2, DRVPDN_MD_PWR_GLOBAL_CON0, DRVPDN_MD_PWR_GLOBAL_SET0, DRVPDN_MD_PWR_GLOBAL_CLR0, MD_PWR_GLOBAL_CON0_SIM2, PDN_OPT_32BIT_REG)
//X_PDN_USER(ADC, DRVPDN_CON1, DRVPDN_CON1_SET, DRVPDN_CON1_CLR, DRVPDN_CON1_ADC, PDN_OPT_16BIT_REG)
//X_PDN_USER(ADC, DRVPDN_CON2, DRVPDN_CON2_SET, DRVPDN_CON2_CLR, DRVPDN_CON2_AUXADC2G, PDN_OPT_16BIT_REG)
//X_PDN_USER(B2SPI, 0, 0, 0, 0, 0)
X_PDN_CONST(GPT, DRVPDN_MD_PWR_GLOBAL_CON0, DRVPDN_MD_PWR_GLOBAL_SET0, DRVPDN_MD_PWR_GLOBAL_CLR0, MD_PWR_GLOBAL_CON0_GPT, PDN_OPT_32BIT_REG)
//X_PDN_USER(PWM, DRVPDN_AP_CG_CON0, DRVPDN_AP_CG_SET0, DRVPDN_AP_CG_CLR0, AP_CG_CON0_PWM, PDN_OPT_32BIT_REG)
//X_PDN_USER(PWM2, 0, 0, 0, 0, 0)
X_PDN_CONST(USB, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_USB0, PDN_OPT_32BIT_REG)
//X_PDN_USER(MSDC, DRVPDN_AP_CG_CON0, DRVPDN_AP_CG_SET0, DRVPDN_AP_CG_CLR0, AP_CG_CON0_MSDC, PDN_OPT_32BIT_REG)
//X_PDN_USER(MSDC2, DRVPDN_CON0, DRVPDN_CON0_SET, DRVPDN_CON0_CLR, DRVPDN_CON0_MSDC2, PDN_OPT_16BIT_REG)
//X_PDN_USER(NFI, DRVPDN_AP_CG_CON0, DRVPDN_AP_CG_SET0, DRVPDN_AP_CG_CLR0, AP_CG_CON0_NFI, PDN_OPT_32BIT_REG)
//X_PDN_USER(IRDA, DRVPDN_CON1, DRVPDN_CON1_SET, DRVPDN_CON1_CLR, DRVPDN_CON1_IRDA, PDN_OPT_16BIT_REG)
//X_PDN_USER(TRC, 0, 0, 0, 0, 0)
//X_PDN_USER(IMGDMA, 0, 0, 0, 0, 0)
//X_PDN_USER(GIF, 0, 0, 0, 0, 0)
//X_PDN_USER(PNG, 0, 0, 0, 0, 0)
//X_PDN_USER(RESZ, 0, 0, 0, 0, 0)

/*
 * Define remaining PDN users.
 * format: X_PDN_CONST(DEVICE_NAME, PDN_CON_REG, PDN_SET_REG, PDN_CLR_REG, PDN_REG_POS, PDN_OPTIONS)
 */

//X_PDN_CONST(ICUSB, DRVPDN_CON0, DRVPDN_CON0_SET, DRVPDN_CON0_CLR, DRVPDN_CON0_USB11, PDN_OPT_16BIT_REG)
//X_PDN_CONST(SEJ, DRVPDN_MD_NONPWR_GLOBAL_CON0, DRVPDN_MD_NONPWR_GLOBAL_SET0, DRVPDN_MD_NONPWR_GLOBAL_CLR0, MD_NONPWR_GLOBAL_CON0_SEJ, PDN_OPT_32BIT_REG)
X_PDN_CONST(TOPSM, DRVPDN_MD_PWR_GLOBAL_CON0, DRVPDN_MD_PWR_GLOBAL_SET0, DRVPDN_MD_PWR_GLOBAL_CLR0, MD_PWR_GLOBAL_CON0_TOPSM, PDN_OPT_32BIT_REG)
X_PDN_CONST(ELM, DRVPDN_MD_PWR_GLOBAL_CON0, DRVPDN_MD_PWR_GLOBAL_SET0, DRVPDN_MD_PWR_GLOBAL_CLR0, MD_PWR_GLOBAL_CON0_ELM, PDN_OPT_32BIT_REG)

//X_PDN_CONST(LOGACC, DRVPDN_CON1, DRVPDN_CON1_SET, DRVPDN_CON1_CLR, DRVPDN_CON1_LOGACC, PDN_OPT_16BIT_REG)
//X_PDN_CONST(TP, DRVPDN_CON1, DRVPDN_CON1_SET, DRVPDN_CON1_CLR, DRVPDN_CON1_TP, PDN_OPT_16BIT_REG)

X_PDN_CONST(TDMA, DRVPDN_MODEM_CG_CON2, DRVPDN_MODEM_CG_SET2, DRVPDN_MODEM_CG_CLR2, MODEM_CG_CON2_TDMA, PDN_OPT_32BIT_REG)
//X_PDN_CONST(RTC, DRVPDN_CON2, DRVPDN_CON2_SET, DRVPDN_CON2_CLR, DRVPDN_CON2_RTC, PDN_OPT_16BIT_REG)
X_PDN_CONST(BSI2G, DRVPDN_MODEM_CG_CON4, DRVPDN_MODEM_CG_SET4, DRVPDN_MODEM_CG_CLR4, MODEM_CG_CON4_BSI_2G, PDN_OPT_32BIT_REG)
X_PDN_CONST(BPI2G, DRVPDN_MODEM_CG_CON4, DRVPDN_MODEM_CG_SET4, DRVPDN_MODEM_CG_CLR4, MODEM_CG_CON4_BPI_2G, PDN_OPT_32BIT_REG)
X_PDN_CONST(AFC2G, DRVPDN_MODEM_CG_CON4, DRVPDN_MODEM_CG_SET4, DRVPDN_MODEM_CG_CLR4, MODEM_CG_CON4_AFC_2G, PDN_OPT_32BIT_REG)
//X_PDN_CONST(APC, DRVPDN_MD2GSYS_CG_CON4, DRVPDN_MD2GSYS_CG_SET4, DRVPDN_MD2GSYS_CG_CLR4, MD2GSYS_CG_CON4_APC, PDN_OPT_16BIT_REG)
X_PDN_CONST(BSI3G, DRVPDN_MODEM_CG_CON0, DRVPDN_MODEM_CG_SET0, DRVPDN_MODEM_CG_CLR0, MODEM_CG_CON0_BSI_3G, PDN_OPT_32BIT_REG)
X_PDN_CONST(BPI3G, DRVPDN_MODEM_CG_CON0, DRVPDN_MODEM_CG_SET0, DRVPDN_MODEM_CG_CLR0, MODEM_CG_CON0_BPI_3G, PDN_OPT_32BIT_REG)
//X_PDN_CONST(MIXED, DRVPDN_CON2, DRVPDN_CON2_SET, DRVPDN_CON2_CLR, DRVPDN_CON2_MIXED, PDN_OPT_16BIT_REG)
X_PDN_CONST(WCDMATIMER, DRVPDN_MODEM_CG_CON0, DRVPDN_MODEM_CG_SET0, DRVPDN_MODEM_CG_CLR0, MODEM_CG_CON0_WTIMER, PDN_OPT_32BIT_REG)
X_PDN_CONST(DIV, DRVPDN_MODEM_CG_CON2, DRVPDN_MODEM_CG_SET2, DRVPDN_MODEM_CG_CLR2, MODEM_CG_CON2_DIVIDER, PDN_OPT_32BIT_REG)
X_PDN_CONST(AFC3G, DRVPDN_MODEM_CG_CON0, DRVPDN_MODEM_CG_SET0, DRVPDN_MODEM_CG_CLR0, MODEM_CG_CON0_AFC_3G, PDN_OPT_32BIT_REG)
//X_PDN_CONST(I2C, DRVPDN_AP_CG_CON0, DRVPDN_AP_CG_SET0, DRVPDN_AP_CG_CLR0, AP_CG_CON0_I2C, PDN_OPT_32BIT_REG)
//X_PDN_CONST(ADC3G, DRVPDN_CON2, DRVPDN_CON2_SET, DRVPDN_CON2_CLR, DRVPDN_CON2_AUXADC3G, PDN_OPT_16BIT_REG)

//X_PDN_CONST(ADC2GTX, DRVPDN_CON3, DRVPDN_CON3_SET, DRVPDN_CON3_CLR, DRVPDN_CON3_AUXADC2GTX, PDN_OPT_16BIT_REG)
//X_PDN_CONST(BTIF, DRVPDN_CON3, DRVPDN_CON3_SET, DRVPDN_CON3_CLR, DRVPDN_CON3_BTIF, PDN_OPT_16BIT_REG)
X_PDN_CONST(OSTIMERARM, DRVPDN_MD_PWR_GLOBAL_CON0, DRVPDN_MD_PWR_GLOBAL_SET0, DRVPDN_MD_PWR_GLOBAL_CLR0, MD_PWR_GLOBAL_CON0_OSTIMER, PDN_OPT_32BIT_REG)
//X_PDN_CONST(OSTIMERDSP, DRVPDN_CON3, DRVPDN_CON3_SET, DRVPDN_CON3_CLR, DRVPDN_CON3_OSTIMERDSP, PDN_OPT_16BIT_REG)
//X_PDN_CONST(FSPI, DRVPDN_CON3, DRVPDN_CON3_SET, DRVPDN_CON3_CLR, DRVPDN_CON3_FSPI, PDN_OPT_16BIT_REG)
//X_PDN_CONST(MSDC3, DRVPDN_CON3, DRVPDN_CON3_SET, DRVPDN_CON3_CLR, DRVPDN_CON3_MSDC3, PDN_OPT_16BIT_REG)
//X_PDN_CONST(PFC, DRVPDN_MD_PWR_GLOBAL_CON0, DRVPDN_MD_PWR_GLOBAL_SET0, DRVPDN_MD_PWR_GLOBAL_CLR0, MD_PWR_GLOBAL_CON0_PFC, PDN_OPT_32BIT_REG)
//X_PDN_CONST(TRNG, DRVPDN_CON3, DRVPDN_CON3_SET, DRVPDN_CON3_CLR, DRVPDN_CON3_TRNG, PDN_OPT_16BIT_REG)
//X_PDN_CONST(MDIF, DRVPDN_CON3, DRVPDN_CON3_SET, DRVPDN_CON3_CLR, DRVPDN_CON3_MDIF, PDN_OPT_16BIT_REG)

//X_PDN_CONST(EQ, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_EQ, PDN_OPT_16BIT_REG)
//X_PDN_CONST(PREEQ, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_PREEQ, PDN_OPT_16BIT_REG)
//X_PDN_CONST(SEQRX, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_SEQRX, PDN_OPT_16BIT_REG)
//X_PDN_CONST(SEQTX, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_SEQTX, PDN_OPT_16BIT_REG)
//X_PDN_CONST(CONV, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_CONV, PDN_OPT_16BIT_REG)
//X_PDN_CONST(FIRE, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_FIRE, PDN_OPT_16BIT_REG)
//X_PDN_CONST(CRC, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_CRC, PDN_OPT_16BIT_REG)
//X_PDN_CONST(ECRCE, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_ECRCE, PDN_OPT_16BIT_REG)
//X_PDN_CONST(ECRCD, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_ECRCD, PDN_OPT_16BIT_REG)
//X_PDN_CONST(ECONV, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_ECONV, PDN_OPT_16BIT_REG)
//X_PDN_CONST(PUNC, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_PUNC, PDN_OPT_16BIT_REG)
//X_PDN_CONST(VITERBI, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_VITERBI, PDN_OPT_16BIT_REG)
//X_PDN_CONST(EAPG, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_EAPG, PDN_OPT_16BIT_REG)
//X_PDN_CONST(ADDRGEN, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_ADDRGEN, PDN_OPT_16BIT_REG)
//X_PDN_CONST(LOG2G, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_LOG2G, PDN_OPT_16BIT_REG)
//X_PDN_CONST(DEINTDMA, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_DEINTDMA, PDN_OPT_16BIT_REG)

X_PDN_CONST(IRDMA, DRVPDN_MD2GSYS_CG_CON0, DRVPDN_MD2GSYS_CG_SET0, DRVPDN_MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_IRDMA, PDN_OPT_16BIT_REG)
X_PDN_CONST(APC_PRE, DRVPDN_MD2GSYS_CG_CON2, DRVPDN_MD2GSYS_CG_SET2, DRVPDN_MD2GSYS_CG_CLR2, MD2GSYS_CG_CON2_APC_PRE, PDN_OPT_16BIT_REG)
X_PDN_CONST(FCS, DRVPDN_MODEM_CG_CON2, DRVPDN_MODEM_CG_SET2, DRVPDN_MODEM_CG_CLR2, MODEM_CG_CON2_FCS, PDN_OPT_32BIT_REG)
X_PDN_CONST(BFE, DRVPDN_MD2GSYS_CG_CON2, DRVPDN_MD2GSYS_CG_SET2, DRVPDN_MD2GSYS_CG_CLR2, MD2GSYS_CG_CON2_BFE, PDN_OPT_16BIT_REG)
X_PDN_CONST(VAFE, DRVPDN_MD2GSYS_CG_CON2, DRVPDN_MD2GSYS_CG_SET2, DRVPDN_MD2GSYS_CG_CLR2, MD2GSYS_CG_CON2_VAFE, PDN_OPT_16BIT_REG)

//X_PDN_CONST(APC, MD2GSYS_CG_CON2, MD2GSYS_CG_SET2, MD2GSYS_CG_CLR2, MD2GSYS_CG_CON2_APC, PDN_OPT_16BIT_REG)

//X_PDN_CONST(GMC, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_GMC, PDN_OPT_32BIT_REG)
//X_PDN_CONST(G2D, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_G2D, PDN_OPT_32BIT_REG)

//X_PDN_CONST(GCMQ, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_GCMQ, PDN_OPT_32BIT_REG)
//X_PDN_CONST(DCT, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_DCT, PDN_OPT_32BIT_REG)

//X_PDN_CONST(JPGENC, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_JPGENC, PDN_OPT_32BIT_REG)
//X_PDN_CONST(MDPMOUT0, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_MDPMOUT0, PDN_OPT_32BIT_REG)
//X_PDN_CONST(JPGDEC, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_JPGDEC, PDN_OPT_32BIT_REG)
//X_PDN_CONST(JPEGDMA, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_JPEGDMA, PDN_OPT_32BIT_REG)
//X_PDN_CONST(OVL, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_OVL, PDN_OPT_32BIT_REG)
//X_PDN_CONST(BRZ, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_BRZ, PDN_OPT_32BIT_REG)
//X_PDN_CONST(IPP, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_IPP, PDN_OPT_32BIT_REG)
//X_PDN_CONST(PRZ, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_PRZ, PDN_OPT_32BIT_REG)
//X_PDN_CONST(CRZ, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_CRZ, PDN_OPT_32BIT_REG)
//X_PDN_CONST(VRZ, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_VRZ, PDN_OPT_32BIT_REG)
//X_PDN_CONST(ROTDMA2, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_ROTDMA2, PDN_OPT_32BIT_REG)
//X_PDN_CONST(GFXROT, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_GFXROT, PDN_OPT_32BIT_REG)
//X_PDN_CONST(RDMA, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_RDMA, PDN_OPT_32BIT_REG)
//X_PDN_CONST(SPI, DRVPDN_AP_CG_CON0, DRVPDN_AP_CG_SET0, DRVPDN_AP_CG_CLR0, AP_CG_CON0_SPI, PDN_OPT_32BIT_REG)
//X_PDN_CONST(ROTDMA0, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_ROTDMA0, PDN_OPT_32BIT_REG)
//X_PDN_CONST(ROTDMA1, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_ROTDMA1, PDN_OPT_32BIT_REG)
//X_PDN_CONST(RESZLB, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_RESZLB, PDN_OPT_32BIT_REG)
//X_PDN_CONST(LCD, DRVPDN_AP_CG_CON0, DRVPDN_AP_CG_SET0, DRVPDN_AP_CG_CLR0, AP_CG_CON0_LCD, PDN_OPT_32BIT_REG)
//X_PDN_CONST(GOVL, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_GOVL, PDN_OPT_32BIT_REG)
//X_PDN_CONST(TDDMA, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_TDDMA, PDN_OPT_32BIT_REG)
//X_PDN_CONST(ITDMA, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_ITDMA, PDN_OPT_32BIT_REG)
//X_PDN_CONST(GIF, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_GIF, PDN_OPT_32BIT_REG)
//X_PDN_CONST(PNG, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_PNG, PDN_OPT_32BIT_REG)
//X_PDN_CONST(MDPMOUT1, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_MDPMOUT1, PDN_OPT_32BIT_REG)
//X_PDN_CONST(OVLBPS, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_OVLBPS, PDN_OPT_32BIT_REG)
//X_PDN_CONST(MMLMU, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_MMLMU, PDN_OPT_32BIT_REG)
//X_PDN_CONST(MDPMOUT2, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_MDPMOUT2, PDN_OPT_32BIT_REG)
//X_PDN_CONST(MDPMOUT3, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_MDPMOUT3, PDN_OPT_32BIT_REG)
//X_PDN_CONST(CAM, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_CAM, PDN_OPT_32BIT_REG)

X_PDN_CONST(HIF, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_MD_HIF, PDN_OPT_32BIT_REG)


//X_PDN_CONST(SFC, DRVPDN_MD_PWR_GLOBAL_CON0, DRVPDN_MD_PWR_GLOBAL_SET0, DRVPDN_MD_PWR_GLOBAL_CLR0, MD_PWR_GLOBAL_CON0_SFC, PDN_OPT_32BIT_REG)
//X_PDN_CONST(TRACE, DRVPDN_MD_PWR_GLOBAL_CON0, DRVPDN_MD_PWR_GLOBAL_SET0, DRVPDN_MD_PWR_GLOBAL_CLR0, MD_PWR_GLOBAL_CON0_TRACE, PDN_OPT_32BIT_REG)
//X_PDN_CONST(LMU, DRVPDN_MD_PWR_GLOBAL_CON0, DRVPDN_MD_PWR_GLOBAL_SET0, DRVPDN_MD_PWR_GLOBAL_CLR0, MD_PWR_GLOBAL_CON0_LMU, PDN_OPT_32BIT_REG)
X_PDN_CONST(ABM, DRVPDN_MD_PWR_GLOBAL_CON0, DRVPDN_MD_PWR_GLOBAL_SET0, DRVPDN_MD_PWR_GLOBAL_CLR0, MD_PWR_GLOBAL_CON0_ABM, PDN_OPT_32BIT_REG)
X_PDN_CONST(ALC, DRVPDN_MD_PWR_GLOBAL_CON0, DRVPDN_MD_PWR_GLOBAL_SET0, DRVPDN_MD_PWR_GLOBAL_CLR0, MD_PWR_GLOBAL_CON0_ALC, PDN_OPT_32BIT_REG)
X_PDN_CONST(ADOE, DRVPDN_MD_PWR_GLOBAL_CON0, DRVPDN_MD_PWR_GLOBAL_SET0, DRVPDN_MD_PWR_GLOBAL_CLR0, MD_PWR_GLOBAL_CON0_ADOE, PDN_OPT_32BIT_REG)
//X_PDN_CONST(TIU_BUFF, DRVPDN_MD_PWR_GLOBAL_CON0, DRVPDN_MD_PWR_GLOBAL_SET0, DRVPDN_MD_PWR_GLOBAL_CLR0, MD_PWR_GLOBAL_CON0_TIU_BUFF, PDN_OPT_32BIT_REG)
X_PDN_CONST(PF_BUFF, DRVPDN_MD_PWR_GLOBAL_CON0, DRVPDN_MD_PWR_GLOBAL_SET0, DRVPDN_MD_PWR_GLOBAL_CLR0, MD_PWR_GLOBAL_CON0_PF_BUFF, PDN_OPT_32BIT_REG)
X_PDN_CONST(BOOT_SLV, DRVPDN_MD_PWR_GLOBAL_CON0, DRVPDN_MD_PWR_GLOBAL_SET0, DRVPDN_MD_PWR_GLOBAL_CLR0, MD_PWR_GLOBAL_CON0_BOOT_SLV, PDN_OPT_32BIT_REG)

/* temporaily commented for UART DVY */
X_PDN_CONST(AP_UART1, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_UART0, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_UART2, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_UART1, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_UART3, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_UART2, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_UART4, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_UART3, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_DMA, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_AP_DMA, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_USB0, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_USB0, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_USB1, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_USB1, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_MSDC2_1, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_MSDC20_1, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_MSDC2_2, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_MSDC20_2, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_MSDC3_1, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_MSDC30_1, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_MSDC3_2, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_MSDC30_2, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_MSDC3_3, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_MSDC30_3, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_NFI, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_NFI, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_NLI, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_NLI, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_HIF, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_AP_HIF, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_PWM1, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_PWM1, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_PWM2, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_PWM2, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_PWM3, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_PWM3, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_PWM4, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_PWM4, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_PWM5, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_PWM5, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_PWM6, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_PWM6, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_PWM7, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_PWM7, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_PWM, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_PWM, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_THERM, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_THERM, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_IRDA, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_IRDA, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_I2C0, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_I2C0, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_I2C1, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_I2C1, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_I2C2, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_I2C2, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_I2C3, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_I2C3, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_I2C4, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_I2C4, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_I2C5, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_I2C5, PDN_OPT_32BIT_REG)
//X_PDN_CONST(AP_CCIF, DRVPDN_AP_CG_CON0, DRVPDN_AP_CG_SET0, DRVPDN_AP_CG_CLR0, AP_CG_CON0_AP_CCIF, PDN_OPT_32BIT_REG)
//X_PDN_CONST(SPI_PAD, DRVPDN_AP_CG_CON0, DRVPDN_AP_CG_SET0, DRVPDN_AP_CG_CLR0, AP_CG_CON0_SPI_PAD, PDN_OPT_32BIT_REG)

//X_PDN_CONST(AP_TRACE, DRVPDN_AP_CG_CON0, DRVPDN_AP_CG_SET0, DRVPDN_AP_CG_CLR0, AP_CG_CON0_AP_TRACE, PDN_OPT_32BIT_REG)
//X_PDN_CONST(TIU, DRVPDN_AP_CG_CON0, DRVPDN_AP_CG_SET0, DRVPDN_AP_CG_CLR0, AP_CG_CON0_TIU, PDN_OPT_32BIT_REG)
//X_PDN_CONST(DBG_FBCLK, DRVPDN_AP_CG_CON0, DRVPDN_AP_CG_SET0, DRVPDN_AP_CG_CLR0, AP_CG_CON0_DBG_FBCLK, PDN_OPT_32BIT_REG)
X_PDN_CONST(GCC, DRVPDN_MD2GSYS_CG_CON0, DRVPDN_MD2GSYS_CG_SET0, DRVPDN_MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_GCC, PDN_OPT_16BIT_REG)
X_PDN_CONST(TXBUF, DRVPDN_MD2GSYS_CG_CON0, DRVPDN_MD2GSYS_CG_SET0, DRVPDN_MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_TXBUF, PDN_OPT_16BIT_REG)
X_PDN_CONST(RXBUF, DRVPDN_MD2GSYS_CG_CON0, DRVPDN_MD2GSYS_CG_SET0, DRVPDN_MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_RXBUF, PDN_OPT_16BIT_REG)
X_PDN_CONST(IRDBG, DRVPDN_MD2GSYS_CG_CON0, DRVPDN_MD2GSYS_CG_SET0, DRVPDN_MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_IRDBG, PDN_OPT_16BIT_REG)
X_PDN_CONST(AHB2DSPIO, DRVPDN_MD2GSYS_CG_CON0, DRVPDN_MD2GSYS_CG_SET0, DRVPDN_MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_AHB2DSPIO, PDN_OPT_16BIT_REG)

X_PDN_CONST(DBG, DRVPDN_MD_PWR_GLOBAL_CON0, DRVPDN_MD_PWR_GLOBAL_SET0, DRVPDN_MD_PWR_GLOBAL_CLR0, MD_PWR_GLOBAL_CON0_DBG, PDN_OPT_32BIT_REG)
//X_PDN_CONST(SDCTL, DRVPDN_MD_NONPWR_GLOBAL_CON0, DRVPDN_MD_NONPWR_GLOBAL_SET0, DRVPDN_MD_NONPWR_GLOBAL_CLR0, MD_NONPWR_GLOBAL_CON0_SDCTL, PDN_OPT_32BIT_REG)
//X_PDN_CONST(MBIST, DRVPDN_MD_NONPWR_GLOBAL_CON0, DRVPDN_MD_NONPWR_GLOBAL_SET0, DRVPDN_MD_NONPWR_GLOBAL_CLR0, MD_NONPWR_GLOBAL_CON0_MBIST, PDN_OPT_32BIT_REG)

X_PDN_CONST(BSIPMIC, DRVPDN_MODEM_CG_CON0, DRVPDN_MODEM_CG_SET0, DRVPDN_MODEM_CG_CLR0, MODEM_CG_CON0_BSI_PMIC, PDN_OPT_32BIT_REG)
X_PDN_CONST(BPIPMIC, DRVPDN_MODEM_CG_CON0, DRVPDN_MODEM_CG_SET0, DRVPDN_MODEM_CG_CLR0, MODEM_CG_CON0_BPI_PMIC, PDN_OPT_32BIT_REG)
X_PDN_CONST(PFCDEC, DRVPDN_MODEM_CG_CON0, DRVPDN_MODEM_CG_SET0, DRVPDN_MODEM_CG_CLR0, MODEM_CG_CON0_PFC_DEC, PDN_OPT_32BIT_REG)
X_PDN_CONST(BYCACC, DRVPDN_MODEM_CG_CON0, DRVPDN_MODEM_CG_SET0, DRVPDN_MODEM_CG_CLR0, MODEM_CG_CON0_BYC_ACC, PDN_OPT_32BIT_REG)
X_PDN_CONST(ATB, DRVPDN_MODEM_CG_CON0, DRVPDN_MODEM_CG_SET0, DRVPDN_MODEM_CG_CLR0, MODEM_CG_CON0_ATB, PDN_OPT_32BIT_REG)
X_PDN_CONST(PFCENC, DRVPDN_MODEM_CG_CON0, DRVPDN_MODEM_CG_SET0, DRVPDN_MODEM_CG_CLR0, MODEM_CG_CON0_PFC_ENC, PDN_OPT_32BIT_REG)
X_PDN_CONST(BSI2G_T, DRVPDN_MODEM_CG_CON2, DRVPDN_MODEM_CG_SET2, DRVPDN_MODEM_CG_CLR2, MODEM_CG_CON2_BSI_2G_T, PDN_OPT_32BIT_REG)
X_PDN_CONST(BPI2G_T, DRVPDN_MODEM_CG_CON2, DRVPDN_MODEM_CG_SET2, DRVPDN_MODEM_CG_CLR2, MODEM_CG_CON2_BPI_2G_T, PDN_OPT_32BIT_REG)
X_PDN_CONST(AFC2G_T, DRVPDN_MODEM_CG_CON2, DRVPDN_MODEM_CG_SET2, DRVPDN_MODEM_CG_CLR2, MODEM_CG_CON2_AFC_2G_T, PDN_OPT_32BIT_REG)


X_PDN_CONST(INFRA_MD1_PMICWRAP, DRVPDN_AP_INFRA_MD1_CG_CON, DRVPDN_AP_INFRA_MD1_CG_SET, DRVPDN_AP_INFRA_MD1_CG_CLR, 
			AP_INFRA_MD1_CON_PMICWRAP, PDN_OPT_32BIT_REG)

X_PDN_CONST(INFRA_MD2_PMICWRAP, DRVPDN_AP_INFRA_MD2_CG_CON, DRVPDN_AP_INFRA_MD2_CG_SET, DRVPDN_AP_INFRA_MD2_CG_CLR, 
			AP_INFRA_MD2_CON_PMICWRAP, PDN_OPT_32BIT_REG)

X_PDN_CONST(INFRA_MD1_PMICSPI, DRVPDN_AP_INFRA_MD1_CG_CON, DRVPDN_AP_INFRA_MD1_CG_SET, DRVPDN_AP_INFRA_MD1_CG_CLR, 
			AP_INFRA_MD1_CON_PMICSPI, PDN_OPT_32BIT_REG)

X_PDN_CONST(INFRA_MD2_PMICSPI, DRVPDN_AP_INFRA_MD2_CG_CON, DRVPDN_AP_INFRA_MD2_CG_SET, DRVPDN_AP_INFRA_MD2_CG_CLR, 
			AP_INFRA_MD2_CON_PMICSPI, PDN_OPT_32BIT_REG)

X_PDN_CONST(TOPCKG_MD1_PMICSPI, DRVPDN_AP_TOPCKGEN_CG_CON, DRVPDN_AP_TOPCKGEN_CG_SET, DRVPDN_AP_TOPCKGEN_CG_CLR, 
			   AP_TOPCKG_MD1_CG_SET_PMICSPI, PDN_OPT_32BIT_REG)

X_PDN_CONST(TOPCKG_MD2_PMICSPI, DRVPDN_AP_TOPCKGEN_CG_CON, DRVPDN_AP_TOPCKGEN_CG_SET, DRVPDN_AP_TOPCKGEN_CG_CLR, 
			   AP_TOPCKG_MD2_CG_SET_PMICSPI, PDN_OPT_32BIT_REG)


/** a especial case for HIF operation, that set/clr 3 bits at one time.
 * 1. MD_HIF PDN should company with AP_HIF PDN, and 
 * 2. DMA PDN is only served for MD_HIF, 
 * thus a combination key is defined for HIF operation.
 **/
X_PDN_CONST(HIF_COMBIN, DRVPDN_AP_PERI_CG_CON0, DRVPDN_AP_PERI_CG_SET0, DRVPDN_AP_PERI_CG_CLR0, AP_PERI_CG_CON0_MD_HIF_COMBIN, PDN_OPT_32BIT_REG)
