/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 *    pdn_def_mt6573_series.h
 *
 * Project:
 * --------
 *   Maui_Software
 *
 * Description:
 * ------------
 *   This file defines PDN X-MACRO for MT6575 series chips.
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

/*
 * Define pre-register PDN users. Need to sync with lpwr.c and register to L1SM.
 * format: X_PDN_USER(DEVICE_NAME, PDN_CON_REG, PDN_SET_REG, PDN_CLR_REG, PDN_REG_POS, PDN_OPTIONS)
 */

X_PDN_CONST(UART1, DRVPDN_CON1, DRVPDN_CON1_SET, DRVPDN_CON1_CLR, DRVPDN_CON1_MDUART1, PDN_OPT_16BIT_REG | PDN_OPT_NEVER_OFF)
X_PDN_CONST(UART2, DRVPDN_CON1, DRVPDN_CON1_SET, DRVPDN_CON1_CLR, DRVPDN_CON1_MDUART2, PDN_OPT_16BIT_REG | PDN_OPT_NEVER_OFF)
//X_PDN_USER(UART3, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_UART3, PDN_OPT_32BIT_REG | PDN_OPT_NEVER_OFF)
//X_PDN_USER(ALTER, 0, 0, 0, 0, 0)
X_PDN_CONST(GCU, DRVPDN_CON3, DRVPDN_CON3_SET, DRVPDN_CON3_CLR, DRVPDN_CON3_GCU, PDN_OPT_16BIT_REG)
X_PDN_CONST(DMA, DRVPDN_CON0, DRVPDN_CON0_SET, DRVPDN_CON0_CLR, DRVPDN_CON0_MDDMA, PDN_OPT_16BIT_REG)
X_PDN_CONST(SIM, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_SIMIF0, PDN_OPT_32BIT_REG)
X_PDN_CONST(SIM2, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_SIMIF1, PDN_OPT_32BIT_REG)
//X_PDN_USER(ADC, DRVPDN_CON1, DRVPDN_CON1_SET, DRVPDN_CON1_CLR, DRVPDN_CON1_ADC, PDN_OPT_16BIT_REG)
X_PDN_CONST(ADC, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_AUXADC, PDN_OPT_32BIT_REG)
//X_PDN_USER(B2SPI, 0, 0, 0, 0, 0)
//X_PDN_USER(GPT, 0, 0, 0, 0, 0)
X_PDN_CONST(PWM, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_PWM1, PDN_OPT_32BIT_REG)
X_PDN_CONST(PWM2, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_PWM2, PDN_OPT_32BIT_REG)
X_PDN_CONST(USB, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_USB, PDN_OPT_32BIT_REG)
X_PDN_CONST(MSDC, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_MSDC, PDN_OPT_32BIT_REG)
X_PDN_CONST(MSDC2, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_MSDC1, PDN_OPT_32BIT_REG)
X_PDN_CONST(NFI, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_NFI, PDN_OPT_32BIT_REG)
X_PDN_CONST(IRDA, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_IRDAFRAMER, PDN_OPT_32BIT_REG)
//X_PDN_USER(TRC, 0, 0, 0, 0, 0)
//X_PDN_USER(IMGDMA, 0, 0, 0, 0, 0)
//X_PDN_USER(RESZ, 0, 0, 0, 0, 0)
//X_PDN_USER(GIF, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_GIF, PDN_OPT_32BIT_REG)
//X_PDN_USER(PNG, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_PNG, PDN_OPT_32BIT_REG)

/*
 * Define remaining PDN users.
 * format: X_PDN_CONST(DEVICE_NAME, PDN_CON_REG, PDN_SET_REG, PDN_CLR_REG, PDN_REG_POS, PDN_OPTIONS)
 */

X_PDN_CONST(DIVIDER, DRVPDN_CON2, DRVPDN_CON2_SET, DRVPDN_CON2_CLR, DRVPDN_CON2_DIVIDER, PDN_OPT_16BIT_REG)
X_PDN_CONST(OSTIMERMDARM, DRVPDN_CON3, DRVPDN_CON3_SET, DRVPDN_CON3_CLR, DRVPDN_CON3_OSTIMERMDARM, PDN_OPT_16BIT_REG)
X_PDN_CONST(OSTIMERFCORE4, DRVPDN_CON3, DRVPDN_CON3_SET, DRVPDN_CON3_CLR, DRVPDN_CON3_OSTIMERFCORE4, PDN_OPT_16BIT_REG)
X_PDN_CONST(AFC2G, DRVPDN_CON4, DRVPDN_CON4_SET, DRVPDN_CON4_CLR, DRVPDN_CON4_AFC2G, PDN_OPT_16BIT_REG)
X_PDN_CONST(BPI2G, DRVPDN_CON4, DRVPDN_CON4_SET, DRVPDN_CON4_CLR, DRVPDN_CON4_BPI2G, PDN_OPT_16BIT_REG)
X_PDN_CONST(DSI2G, DRVPDN_CON4, DRVPDN_CON4_SET, DRVPDN_CON4_CLR, DRVPDN_CON4_BSI2G, PDN_OPT_16BIT_REG)
X_PDN_CONST(TDMA, DRVPDN_CON2, DRVPDN_CON2_SET, DRVPDN_CON2_CLR, DRVPDN_CON2_TDMA, PDN_OPT_16BIT_REG)
X_PDN_CONST(WCDMATIMER, DRVPDN_CON2, DRVPDN_CON2_SET, DRVPDN_CON2_CLR, DRVPDN_CON2_WCDMATIMER, PDN_OPT_16BIT_REG)
X_PDN_CONST(PFC, DRVPDN_CON3, DRVPDN_CON3_SET, DRVPDN_CON3_CLR, DRVPDN_CON3_PFC, PDN_OPT_16BIT_REG)
X_PDN_CONST(LOGACC, DRVPDN_CON1, DRVPDN_CON1_SET, DRVPDN_CON1_CLR, DRVPDN_CON1_LOGACC, PDN_OPT_16BIT_REG)
X_PDN_CONST(AFC3G, DRVPDN_CON2, DRVPDN_CON2_SET, DRVPDN_CON2_CLR, DRVPDN_CON2_AFC3G, PDN_OPT_16BIT_REG)
X_PDN_CONST(BPI3G, DRVPDN_CON2, DRVPDN_CON2_SET, DRVPDN_CON2_CLR, DRVPDN_CON2_BPI3G, PDN_OPT_16BIT_REG)
X_PDN_CONST(BSI3G, DRVPDN_CON2, DRVPDN_CON2_SET, DRVPDN_CON2_CLR, DRVPDN_CON2_BSI3G, PDN_OPT_16BIT_REG)
X_PDN_CONST(MDIF, DRVPDN_CON3, DRVPDN_CON3_SET, DRVPDN_CON3_CLR, DRVPDN_CON3_MDIF, PDN_OPT_16BIT_REG)

//X_PDN_CONST(UART4, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_UART4, PDN_OPT_32BIT_REG | PDN_OPT_NEVER_OFF)
X_PDN_CONST(APDMA, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_APDMA, PDN_OPT_32BIT_REG)
X_PDN_CONST(MSDC3, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_MSDC2, PDN_OPT_32BIT_REG)
X_PDN_CONST(MSDC4, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_MSDC3, PDN_OPT_32BIT_REG)
X_PDN_CONST(USB2, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_USB11, PDN_OPT_32BIT_REG)
//X_PDN_CONST(ADC2, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_AUXADC3G, PDN_OPT_32BIT_REG)
X_PDN_CONST(KP, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_KP, PDN_OPT_32BIT_REG)

X_PDN_CONST(AFC2GPRE, DRVPDN_CON2, DRVPDN_CON2_SET, DRVPDN_CON2_CLR, DRVPDN_CON2_AFC2GPRE, PDN_OPT_16BIT_REG)
X_PDN_CONST(BPI2GPRE, DRVPDN_CON2, DRVPDN_CON2_SET, DRVPDN_CON2_CLR, DRVPDN_CON2_BPI2GPRE, PDN_OPT_16BIT_REG)
X_PDN_CONST(DSI2GPRE, DRVPDN_CON2, DRVPDN_CON2_SET, DRVPDN_CON2_CLR, DRVPDN_CON2_BSI2GPRE, PDN_OPT_16BIT_REG)

//X_PDN_CONST(TP, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_TP, PDN_OPT_32BIT_REG)
//X_PDN_CONST(2GTX, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_2GTX, PDN_OPT_32BIT_REG)
X_PDN_CONST(CCIF, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_CCIF, PDN_OPT_32BIT_REG)

//X_PDN_CONST(OSTIMERAPARM, AP_DRVPDN_CON1, AP_DRVPDN_CON1_SET, AP_DRVPDN_CON1_CLR, AP_DRVPDN_CON1_OSTIMERAPARM, PDN_OPT_32BIT_REG)
X_PDN_CONST(MIXEDSYS, DRVPDN_CON2, DRVPDN_CON2_SET, DRVPDN_CON2_CLR, DRVPDN_CON2_MDMIXED_SYS, PDN_OPT_16BIT_REG)
X_PDN_CONST(I2C, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_I2C, PDN_OPT_32BIT_REG)
X_PDN_CONST(I2C2, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_I2C2, PDN_OPT_32BIT_REG)

X_PDN_CONST(SEJ, AP_DRVPDN_CON1, AP_DRVPDN_CON1_SET, AP_DRVPDN_CON1_CLR, AP_DRVPDN_CON1_SEJ, PDN_OPT_32BIT_REG)
//X_PDN_CONST(HDQONEWIRE, AP_DRVPDN_CON1, AP_DRVPDN_CON1_SET, AP_DRVPDN_CON1_CLR, AP_DRVPDN_CON1_HDQONEWIRE, PDN_OPT_32BIT_REG)
X_PDN_CONST(TRNG, AP_DRVPDN_CON1, AP_DRVPDN_CON1_SET, AP_DRVPDN_CON1_CLR, AP_DRVPDN_CON1_TRNG, PDN_OPT_32BIT_REG)

X_PDN_CONST(MD_HIF, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_MDHIF, PDN_OPT_32BIT_REG)
X_PDN_CONST(AP_HIF, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_APHIF, PDN_OPT_32BIT_REG)
X_PDN_CONST(APXT, AP_DRVPDN_CON0, AP_DRVPDN_CON0_SET, AP_DRVPDN_CON0_CLR, AP_DRVPDN_CON0_APXTIMER, PDN_OPT_32BIT_REG)

X_PDN_CONST(EQ, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_EQ, PDN_OPT_16BIT_REG)
X_PDN_CONST(PREEQ, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_PREEQ, PDN_OPT_16BIT_REG)
X_PDN_CONST(SEQRX, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_SEQRX, PDN_OPT_16BIT_REG)
X_PDN_CONST(SEQTX, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_SEQTX, PDN_OPT_16BIT_REG)
X_PDN_CONST(CONV, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_CONV, PDN_OPT_16BIT_REG)
X_PDN_CONST(FIRE, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_FIRE, PDN_OPT_16BIT_REG)
X_PDN_CONST(CRC, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_CRC, PDN_OPT_16BIT_REG)
X_PDN_CONST(ECRCE, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_ECRCE, PDN_OPT_16BIT_REG)
X_PDN_CONST(ECRCD, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_ECRCD, PDN_OPT_16BIT_REG)
X_PDN_CONST(ECONV, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_ECONV, PDN_OPT_16BIT_REG)
X_PDN_CONST(PUNC, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_PUNC, PDN_OPT_16BIT_REG)
X_PDN_CONST(VITERBI, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_VITERBI, PDN_OPT_16BIT_REG)
X_PDN_CONST(EAPG, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_EAPG, PDN_OPT_16BIT_REG)
X_PDN_CONST(ADDRGEN, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_ADDRGEN, PDN_OPT_16BIT_REG)
//X_PDN_CONST(LOG2G, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_LOG2G, PDN_OPT_16BIT_REG)
X_PDN_CONST(DEINTDMA, MD2GSYS_CG_CON0, MD2GSYS_CG_SET0, MD2GSYS_CG_CLR0, MD2GSYS_CG_CON0_DEINTDMA, PDN_OPT_16BIT_REG)

X_PDN_CONST(IRDMA, MD2GSYS_CG_CON1, MD2GSYS_CG_SET1, MD2GSYS_CG_CLR1, MD2GSYS_CG_CON1_IRDMA, PDN_OPT_16BIT_REG)
X_PDN_CONST(APCPRE, MD2GSYS_CG_CON1, MD2GSYS_CG_SET1, MD2GSYS_CG_CLR1, MD2GSYS_CG_CON1_APCPRE, PDN_OPT_16BIT_REG)
X_PDN_CONST(FCS, DRVPDN_CON3, DRVPDN_CON3_SET, DRVPDN_CON3_CLR, DRVPDN_CON3_FCS, PDN_OPT_16BIT_REG)
X_PDN_CONST(BFE, MD2GSYS_CG_CON1, MD2GSYS_CG_SET1, MD2GSYS_CG_CLR1, MD2GSYS_CG_CON1_BFE, PDN_OPT_16BIT_REG)
X_PDN_CONST(GCCTX, MD2GSYS_CG_CON1, MD2GSYS_CG_SET1, MD2GSYS_CG_CLR1, MD2GSYS_CG_CON1_GCCTX, PDN_OPT_16BIT_REG)
X_PDN_CONST(GCCRX, MD2GSYS_CG_CON1, MD2GSYS_CG_SET1, MD2GSYS_CG_CLR1, MD2GSYS_CG_CON1_GCCRX, PDN_OPT_16BIT_REG)

X_PDN_CONST(APC, MD2GSYS_CG_CON2, MD2GSYS_CG_SET2, MD2GSYS_CG_CLR2, MD2GSYS_CG_CON2_APC, PDN_OPT_16BIT_REG)

X_PDN_CONST(EMI_SMI_LARB2, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_EMI_SMI_LARB2, PDN_OPT_32BIT_REG)
X_PDN_CONST(EMI_EMI_ACP_SMI_LARB2, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_EMI_ACP_SMI_LARB2, PDN_OPT_32BIT_REG)
X_PDN_CONST(EMI_SMI_LARB1, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_EMI_SMI_LARB1, PDN_OPT_32BIT_REG)
X_PDN_CONST(EMI_SMI_LARB0, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_EMI_SMI_LARB0, PDN_OPT_32BIT_REG)
X_PDN_CONST(VBUF, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_VBUF, PDN_OPT_32BIT_REG)
X_PDN_CONST(VDEC, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_VDEC, PDN_OPT_32BIT_REG)
X_PDN_CONST(VENC, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_VENC, PDN_OPT_32BIT_REG)
X_PDN_CONST(ACP_SMI_LARB2, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_ACP_SMI_LARB2, PDN_OPT_32BIT_REG)
X_PDN_CONST(SMI_LARB2, MMSYS_CG_CON0, MMSYS_CG_SET0, MMSYS_CG_CLR0, MMSYS_CG_CON0_SMI_LARB2, PDN_OPT_32BIT_REG)

X_PDN_CONST(VRZ1, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_VRZ1, PDN_OPT_32BIT_REG)
X_PDN_CONST(CSI2, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_CSI2, PDN_OPT_32BIT_REG)
X_PDN_CONST(FD, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_FD, PDN_OPT_32BIT_REG)
X_PDN_CONST(RESZLB, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_RESZLB, PDN_OPT_32BIT_REG)
X_PDN_CONST(TVROT, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_TVROT, PDN_OPT_32BIT_REG)
X_PDN_CONST(LCD, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_LCD, PDN_OPT_32BIT_REG)
X_PDN_CONST(RGBROT2, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_RGB_ROT2, PDN_OPT_32BIT_REG)
X_PDN_CONST(PRZ1, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_PRZ1, PDN_OPT_32BIT_REG)
X_PDN_CONST(RDMA1, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_RDMA1, PDN_OPT_32BIT_REG)
X_PDN_CONST(VDOROT1, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_VDO_ROT1, PDN_OPT_32BIT_REG)
X_PDN_CONST(RGBROT1, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_RGB_ROT1, PDN_OPT_32BIT_REG)
X_PDN_CONST(VRZ, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_VRZ, PDN_OPT_32BIT_REG)
X_PDN_CONST(RGBROT, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_RGB_ROT0, PDN_OPT_32BIT_REG)
X_PDN_CONST(PRZMOUT, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_PRZ0_MOUT, PDN_OPT_32BIT_REG)
X_PDN_CONST(PRZ, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_PRZ0, PDN_OPT_32BIT_REG)
X_PDN_CONST(VDOROT, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_VDO_ROT0, PDN_OPT_32BIT_REG)
X_PDN_CONST(MOUT, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_MOUT, PDN_OPT_32BIT_REG)
X_PDN_CONST(OVLDMA_MIMO, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_OVL_DMA_MIMO, PDN_OPT_32BIT_REG)
X_PDN_CONST(OVLDMA_BPS, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_OVL_DMA_BPS, PDN_OPT_32BIT_REG)
X_PDN_CONST(OVLDMA, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_OVL_DMA, PDN_OPT_32BIT_REG)
X_PDN_CONST(IPPMOUT, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_IPP_MOUT, PDN_OPT_32BIT_REG)
X_PDN_CONST(IPP, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_IPP, PDN_OPT_32BIT_REG)
X_PDN_CONST(EIS, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_EIS, PDN_OPT_32BIT_REG)
X_PDN_CONST(CRZ, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_CRZ, PDN_OPT_32BIT_REG)
X_PDN_CONST(JPGDMA, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_JPG_DMA, PDN_OPT_32BIT_REG)
X_PDN_CONST(BRZMOUT, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_BRZ_MOUT, PDN_OPT_32BIT_REG)
X_PDN_CONST(BRZ, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_BRZ, PDN_OPT_32BIT_REG)
X_PDN_CONST(JPGENC, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_JPG_ENC, PDN_OPT_32BIT_REG)
X_PDN_CONST(JPGDEC, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_JPG_DEC, PDN_OPT_32BIT_REG)
X_PDN_CONST(RDMAMOUT, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_RDMA0_MOUT, PDN_OPT_32BIT_REG)
X_PDN_CONST(RDMA, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_RDMA0, PDN_OPT_32BIT_REG)
X_PDN_CONST(CAM, MMSYS_CG_CON1, MMSYS_CG_SET1, MMSYS_CG_CLR1, MMSYS_CG_CON1_CAM, PDN_OPT_32BIT_REG)

X_PDN_CONST(SCAM, MMSYS_CG_CON2, MMSYS_CG_SET2, MMSYS_CG_CLR2, MMSYS_CG_CON2_SCAM, PDN_OPT_32BIT_REG)
X_PDN_CONST(SPI, MMSYS_CG_CON2, MMSYS_CG_SET2, MMSYS_CG_CLR2, MMSYS_CG_CON2_SPI, PDN_OPT_32BIT_REG)
X_PDN_CONST(DSI, MMSYS_CG_CON2, MMSYS_CG_SET2, MMSYS_CG_CLR2, MMSYS_CG_CON2_DSI, PDN_OPT_32BIT_REG)
X_PDN_CONST(TVC, MMSYS_CG_CON2, MMSYS_CG_SET2, MMSYS_CG_CLR2, MMSYS_CG_CON2_TVC, PDN_OPT_32BIT_REG)
X_PDN_CONST(TVE, MMSYS_CG_CON2, MMSYS_CG_SET2, MMSYS_CG_CLR2, MMSYS_CG_CON2_TVE, PDN_OPT_32BIT_REG)
X_PDN_CONST(DPI, MMSYS_CG_CON2, MMSYS_CG_SET2, MMSYS_CG_CLR2, MMSYS_CG_CON2_DPI, PDN_OPT_32BIT_REG)
X_PDN_CONST(SMILARB0_H, MMSYS_CG_CON2, MMSYS_CG_SET2, MMSYS_CG_CLR2, MMSYS_CG_CON2_H_SMI_LARB0, PDN_OPT_32BIT_REG)
X_PDN_CONST(SMILARB1_H, MMSYS_CG_CON2, MMSYS_CG_SET2, MMSYS_CG_CLR2, MMSYS_CG_CON2_H_SMI_LARB1, PDN_OPT_32BIT_REG)
X_PDN_CONST(SMILARB2_H, MMSYS_CG_CON2, MMSYS_CG_SET2, MMSYS_CG_CLR2, MMSYS_CG_CON2_H_SMI_LARB2, PDN_OPT_32BIT_REG)

X_PDN_CONST(SMI_LARB3, MMSYS2_CG_CON0, MMSYS2_CG_SET0, MMSYS2_CG_CLR0, MMSYS2_CG_CON0_SMI_LARB3, PDN_OPT_32BIT_REG)
X_PDN_CONST(SMIG2D, MMSYS2_CG_CON0, MMSYS2_CG_SET0, MMSYS2_CG_CLR0, MMSYS2_CG_CON0_SMI_G2D, PDN_OPT_32BIT_REG)
X_PDN_CONST(MFG, MMSYS2_CG_CON0, MMSYS2_CG_SET0, MMSYS2_CG_CLR0, MMSYS2_CG_CON0_MFG, PDN_OPT_32BIT_REG)
X_PDN_CONST(G3D, MMSYS2_CG_CON0, MMSYS2_CG_SET0, MMSYS2_CG_CLR0, MMSYS2_CG_CON0_G3D, PDN_OPT_32BIT_REG)
X_PDN_CONST(SMI_LARB3_H, MMSYS2_CG_CON0, MMSYS2_CG_SET0, MMSYS2_CG_CLR0, MMSYS2_CG_CON0_H_SMI_LARB3, PDN_OPT_32BIT_REG)
X_PDN_CONST(MFG_H, MMSYS2_CG_CON0, MMSYS2_CG_SET0, MMSYS2_CG_CLR0, MMSYS2_CG_CON0_H_MFG, PDN_OPT_32BIT_REG)



