copy /y .\service\kal\include\kal_general_types.h %1
copy /y .\service\kal\include\kal_public_defs.h %1
copy /y .\service\config\include\stack_config.h %1
copy /y .\service\kal\include\clib.h %1
copy /y .\interface\driver\peripheral\dcl.h %1
copy /y .\service\config\include\hisr_config_internal.h %1
copy /y .\service\config\include\app_task_config.h %1
copy /y .\service\config\include\hal_task_config.h %1
copy /y .\service\config\include\stack_msgs.h %1
copy /y .\service\kal\include\kal_public_api.h %1
copy /y .\interface\service\tst\kal_trace.h %1
copy /y .\driver\drv_def\drv_features_gpio.h %1
copy /y .\interface\service\nvram\nvram_defs.h %1
copy /y .\driver\drv_def\drv_features_chip_select.h %1
copy /y .\driver\drv_def\drv_features_6280.h %1
copy /y .\interface\modem\ps_public_enum.h %1
copy /y .\driver\sys_drv\regbase\inc\reg_base.h %1
copy /y .\driver\sys_drv\regbase\inc\reg_base_mt6280.h %1
copy /y .\service\config\include\stack_ltlcom.h %1
copy /y .\interface\driver\peripheral\dcl_gpio.h %1
copy /y .\interface\driver\peripheral\dcl_msdc.h %1
copy /y .\interface\driver\peripheral\dcl_pmu.h %1
copy /y .\interface\driver\peripheral\dcl_gpt.h %1
copy /y .\interface\driver\peripheral\dcl_f32k_clk.h %1
copy /y .\interface\driver\peripheral\dcl_sim.h %1
copy /y .\interface\driver\peripheral\dcl_adc.h %1
copy /y .\interface\driver\peripheral\dcl_uart.h %1
copy /y .\interface\driver\peripheral\dcl_chr_det.h %1
copy /y .\interface\driver\peripheral\dcl_sts.h %1
copy /y .\interface\driver\connectivity\usb_driver\dcl_usb_drv.h %1
copy /y .\interface\driver\peripheral\dcl_bmt.h %1
copy /y .\interface\driver\peripheral\dcl_pfc.h %1
copy /y .\interface\driver\peripheral\dcl_pw.h %1
copy /y .\interface\driver\peripheral\dcl_rtc.h %1
copy /y .\interface\driver\peripheral\dcl_sim_gpio.h %1
copy /y .\interface\driver\peripheral\dcl_wdt.h %1
copy /y .\interface\driver\peripheral\DclH_kbd.h %1
copy /y .\interface\driver\peripheral\DclS_kbd.h %1
copy /y .\interface\service\nvram\nvram_enums.h %1
copy /y .\interface\modem\ps_public_struct.h %1
copy /y .\interface\modem\cmux_vp_num.h %1
copy /y .\interface\sap\sap_range.h %1
copy /y .\interface\common\global_def.h %1
copy /y .\service\config\include\stack_buff_pool.h %1
copy /y .\custom\service\nvram\custom_nvram_sec.h %1
copy /y .\service\config\include\ctrl_buff_pool.h %1
copy /y .\driver\drv_def\drv_features_adc.h %1
copy /y .\interface\sap\module_msg_range.h %1
copy /y .\modem\interface\l4misc\l3_inc_enums.h %1
copy /y .\interface\modem\sim_public_enum.h %1
copy /y .\driver\drv_def\drv_features_rtc.h %1
copy /y .\driver\drv_def\drv_features_sim.h %1
copy /y .\interface\modem\sim_ps_enum.h %1
copy /y .\interface\driver\sys_drv\intrCtrl.h %1
copy /y .\driver\sys_drv\cirq\inc\intrCtrl_MT6280.h %1
copy /y .\driver\sys_drv\cirq\inc\intrCtrl_MT6280_SW_Handle.h %1
copy /y .\driver\sys_drv\cirq\inc\intrCtrl_SW_Handle.h %1
copy /y .\interface\modem\l1\fdd\ul1d_rf_cid.h %1
copy /y .\interface\driver\peripheral\dcl_i2c.h %1
copy /y .\interface\driver\peripheral\dcl_i2c_owner.h %1
copy /y .\service\kal\stacklib\include\lcd_ip_cqueue.h %1
copy /y .\interface\driver\connectivity\usb_driver\dcl_otg_drv.h %1
copy /y .\interface\driver\connectivity\usb_driver\dcl_usb_hcd.h %1
copy /y .\interface\driver\peripheral\dcl_aux.h %1
copy /y .\interface\driver\peripheral\dcl_irda.h %1
copy /y .\interface\driver\peripheral\dcl_pwm.h %1
copy /y .\interface\driver\peripheral\dcl_pxs.h %1
copy /y .\service\event_info\event_info_utility.h %1
copy /y .\modem\gl1\l1_dm\common\l1_const.h %1
copy /y .\interface\driver\peripheral\drv_comm.h %1
copy /y .\interface\modem\l1\gsm\mph_types.h %1
copy /y .\interface\service\nvram\nvram_data_items.h %1
copy /y .\service\config\include\stack_types.h %1
copy /y .\interface\modem\l1\fdd\ul1d_rf_public.h %1
copy /y .\interface\modem\l1\fdd\ul1_cnst.h %1
copy /y .\service\config\include\task_config.h %1
copy /y .\interface\sap\svc\sysservice_msgid.h %1
copy /y .\service\config\include\kal_user_mem.h %1
copy /y .\modem\interface\as_common.h %1
copy /y .\interface\sap\md_drv_sap.h %1
copy /y .\service\config\include\sysconf_statistics.h %1
copy /y .\modem\gl1\l1_dm\l1d_ext\l1d_cid.h %1
copy /y .\interface\modem\l1\fdd\ul1_def.h %1
copy /y .\service\sst\include\ex_item.h %1
copy /y .\interface\modem\ps_em_enum.h %1
copy /y .\interface\modem\em_public_struct.h %1
copy /y .\interface\modem\l1\fdd\ul1cal.h %1
copy /y .\service\tst\include\tst.h %1
copy /y .\driver\drv_def\drv_features_gpt.h %1
copy /y .\driver\drv_def\drv_features_f8f9bc.h %1
copy /y .\modem\interface\l4misc\l3_inc_local.h %1
copy /y .\driver\drv_def\drv_features_wdt.h %1
copy /y .\service\kal\include\clib_list.h %1
copy /y .\driver\drv_def\drv_features_pwm.h %1
copy /y .\service\kal\stacklib\include\lcd.h %1
copy /y .\driver\drv_def\drv_features_f32k.h %1
copy /y .\driver\drv_def\drv_features_uart.h %1
copy /y .\driver\drv_def\drv_features_i2c.h %1
copy /y .\driver\drv_def\drv_features_gcu.h %1
copy /y .\service\nucleus_v2\inc\nucleus.h %1
copy /y .\driver\drv_def\drv_features.h %1
copy /y .\driver\drv_def\drv_features_accdet.h %1
copy /y .\driver\drv_def\drv_features_bmt.h %1
copy /y .\driver\drv_def\drv_features_hif.h %1
copy /y .\driver\drv_def\drv_features_misc.h %1
copy /y .\driver\drv_def\drv_features_msdc.h %1
copy /y .\driver\drv_def\drv_features_pfc.h %1
copy /y .\driver\drv_def\drv_features_spi.h %1
copy /y .\driver\drv_def\drv_features_usb.h %1
copy /y .\interface\service\fs\fs_gprot.h %1
copy /y .\modem\interface\l1\inner\l1_types.h %1
copy /y .\interface\modem\sim_common_enums.h %1
copy /y .\service\kal\stacklib\include\lcd_lqueue.h %1
copy /y .\modem\interface\uas_common_enums.h %1
copy /y .\modem\interface\l1\inner\l1_core_private.h %1
copy /y .\interface\modem\em_struct.h %1
copy /y .\modem\gl1\l1_dm\common\tool.h %1
copy /y .\interface\modem\sim_public_api.h %1
copy /y .\service\tst\include\L1Trc.h %1
copy /y .\interface\driver\sys_drv\cache_sw.h %1
copy /y .\interface\modem\sim_ps_api.h %1
copy /y .\interface\sap\md_sap.h %1
copy /y .\service\kal\stacklib\include\lcd_cqueue.h %1
copy /y .\service\asn1_common\mtkasn_global.h %1
copy /y .\interface\modem\l1\gsm\l1_types_public.h %1
copy /y .\modem\interface\l1\inner\l1_tool.h %1
copy /y .\modem\interface\l1\inner\l1_public.h %1
copy /y .\modem\interface\l1\gsm\mph_cnst.h %1
copy /y .\service\fs\common\include\fs_internal_def.h %1
copy /y .\interface\sap\svc_sap.h %1
copy /y .\modem\interface\l1\inner\l1_core.h %1
copy /y .\modem\ul1\ul1_hs_plus\common\ul1_types.h %1
copy /y .\service\kal\common\include\stack_timer.h %1
copy /y .\service\tst\include\MalmoDriver.h %1
copy /y .\service\nucleus_v2\inc\tc_defs.h %1
copy /y .\service\tst\include\tst_lmu_hw.h %1
copy /y .\service\nucleus_v2\inc\esal_ar_cfg.h %1
copy /y .\service\nucleus_v2\inc\esal_ar_dbg_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_ar_int_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_ar_isr_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_ar_stk_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_ar_tmr_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_co_cfg.h %1
copy /y .\service\nucleus_v2\inc\esal_dp_cfg.h %1
copy /y .\service\nucleus_v2\inc\esal_extern.h %1
copy /y .\service\nucleus_v2\inc\esal_ge_cfg.h %1
copy /y .\service\nucleus_v2\inc\esal_ge_com_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_ge_dbg_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_ge_int_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_ge_isr_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_ge_mem_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_ge_rte_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_ge_stk_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_ge_tmr_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_pr_cfg.h %1
copy /y .\service\nucleus_v2\inc\esal_pr_tmr_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_ts_cfg.h %1
copy /y .\service\nucleus_v2\inc\esal_ts_rte_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_ts_stk_defs.h %1
copy /y .\interface\modem\flc2_config.h %1
copy /y .\custom\modem\ul1_rf\MT6280RF_UMTS_FDD\ul1d_custom_rf.h %1
copy /y .\interface\modem\l1\fdd\ul1d_rf_common.h %1
copy /y .\service\nucleus_v2\inc\cs_defs.h %1
copy /y .\service\tst\include\L1Trc_lmu.h %1
copy /y .\modem\interface\uas_gas_enums.h %1
copy /y .\service\nucleus_v2\inc\pm_defs.h %1
copy /y .\service\nucleus_v2\inc\tm_defs.h %1
copy /y .\service\nucleus_v2\inc\ev_defs.h %1
copy /y .\service\nucleus_v2\inc\qu_defs.h %1
copy /y .\service\nucleus_v2\inc\sm_defs.h %1
copy /y .\service\nucleus_v2\inc\dm_defs.h %1
copy /y .\service\nucleus_v2\inc\er_extr.h %1
copy /y .\service\nucleus_v2\inc\mb_defs.h %1
copy /y .\service\nucleus_v2\inc\pi_defs.h %1
copy /y .\service\nucleus_v2\inc\plus_cfg.h %1
copy /y .\service\nucleus_v2\inc\zc_extr.h %1
copy /y .\modem\interface\l1\inner\l1_private.h %1
copy /y .\service\fsm\include\sm_type.h %1
copy /y .\driver\sleep_drv\inc\dcxo_div.h %1
copy /y .\modem\interface\divider_public.h %1
copy /y .\modem\interface\l1\inner\l1_timertype.h %1
copy /y .\modem\uas\interface\local_inc\uas_common_struct.h %1
copy /y .\interface\driver\peripheral\adc_cali.h %1
copy /y .\interface\modem\l1\fdd\ul1_struct.h %1
copy /y .\modem\ul1\ul1_hs_plus\ul1d\ul1d_cid.h %1
copy /y .\interface\service\fs\fs_type.h %1
copy /y .\modem\interface\l3llc_enums.h %1
copy /y .\modem\gas\common\include\rr_common_def.h %1
copy /y .\modem\gas\common\include\rr_mpal_interface.h %1
copy /y .\modem\interface\asn\rr\include\csn_common.h %1
copy /y .\interface\modem\device.h %1
copy /y .\interface\modem\l1\gsm\l1_interface.h %1
copy /y .\modem\interface\asn\rr\include\gprs_rlcmac_common_struct.h %1
copy /y .\modem\interface\rlc_mac_enums.h %1
copy /y .\interface\modem\tcm_api.h %1
copy /y .\modem\gas\common\include\rr_context.h %1
copy /y .\service\kal\stacklib\include\stacklib.h %1
copy /y .\modem\interface\rr2mpal_struct.h %1
copy /y .\service\asn1_common\asn_memory.h %1
copy /y .\modem\interface\l1\inner\ul1_timertype.h %1
copy /y .\custom\modem\common\ps\ul1_nvram_def.h %1
copy /y .\service\asn1_common\asn_common.h %1
copy /y .\service\kal\common\include\kal_debug.h %1
copy /y .\service\kal\mlib\include\mlib_dll.h %1
copy /y .\modem\interface\asn\rr\include\gprs_rlcmac_dl_struct.h %1
copy /y .\interface\modem\l4c_msg_hdlr_defs.h %1
copy /y .\service\kal\common\include\event_shed.h %1
copy /y .\interface\sap\md\l4_msgid.h %1
copy /y .\modem\gas\common\include\psi_si_common.h %1
copy /y .\interface\service\nvram\nvram_editor_data_item.h %1
copy /y .\service\nucleus_v2\inc\tm_extr.h %1
copy /y .\modem\gas\common\include\si.h %1
copy /y .\interface\modem\smu_common_enums.h %1
copy /y .\modem\common\mcd\include\mcd_struct.h %1
copy /y .\interface\modem\flc2_ent_functions.h %1
copy /y .\service\kal\stacklib\include\dlist.h %1
copy /y .\modem\interface\l4misc\l4c_common_enum.h %1
copy /y .\service\config\include\hisr_config.h %1
copy /y .\modem\interface\l1\inner\ul1_public.h %1
copy /y .\modem\interface\mcd\include\mcd.h %1
copy /y .\modem\interface\l1\inner\ul1_option.h %1
copy /y .\modem\interface\asn\rr\include\gprs_rlcmac_ul_struct.h %1
copy /y .\driver\sys_drv\pdn\inc\pdn_def.h %1
copy /y .\service\kal\common\include\kal_debug_common_defs.h %1
copy /y .\service\kal\common\include\kal_error_code.h %1
copy /y .\service\kal\common\include\kal_internal_api.h %1
copy /y .\service\kal\nucleus\include\kal_debug_nucleus.h %1
copy /y .\service\kal\nucleus\include\kal_nucleus.h %1
copy /y .\service\kal\nucleus\include\kal_nucleus_common_defs.h %1
copy /y .\service\config\include\syscomp_config.h %1
copy /y .\driver\drv_def\drv_features_mmsysmisc.h %1
copy /y .\interface\driver\drv_sw_def\drv_sw_features_mmsysmisc.h %1
copy /y .\interface\modem\sim_public_struct.h %1
copy /y .\driver\sys_drv\pdn\inc\pdn_hw_mt6280_series.h %1
copy /y .\driver\sys_drv\pdn\inc\pdn_hw_series.h %1
copy /y .\modem\interface\asn\rr\include\rmc_peer_dl_struct.h %1
copy /y .\service\fsm\include\sm_event.h %1
copy /y .\modem\gas\rrm\rmc\include\meas_context.h %1
copy /y .\driver\sys_drv\pdn\inc\drvpdn.h %1
copy /y .\driver\sys_drv\pdn\inc\pdn_def_mt6280_series.h %1
copy /y .\modem\common\mcd\include\mcd_enum.h %1
copy /y .\modem\gas\rrm\common\include\rrm_context.h %1
copy /y .\interface\middleware\meta\ul1tst_msg.h %1
copy /y .\interface\modem\mmi_l3_enums.h %1
copy /y .\modem\interface\asn\rr\include\error_struct_enum.h %1
copy /y .\interface\modem\sim_ps_struct.h %1
copy /y .\service\sys_svc\gfh\public\br_GFH.h %1
copy /y .\modem\interface\uas_gas_struct.h %1
copy /y .\modem\interface\as2nas_struct.h %1
copy /y .\modem\interface\l4misc\l4c2phb_enums.h %1
copy /y .\modem\gas\common\include\rr_data_ind.h %1
copy /y .\modem\uas\ul2\common\include\rlc_cid.h %1
copy /y .\modem\interface\asn\rr\include\mtkcsn_global.h %1
copy /y .\driver\sys_drv\init\inc\init.h %1
copy /y .\interface\service\sys_svc\init_public.h %1
copy /y .\modem\interface\l1\gsm\mph_cs_def.h %1
copy /y .\modem\gas\common\include\rr_common_headers.h %1
copy /y .\modem\interface\asn\asn1lib\include\asn1lib.h %1
copy /y .\modem\uas\ul2\common\include\ul2_common_def.h %1
copy /y .\modem\uas\interface\enum\cmac_enums.h %1
copy /y .\modem\uas\interface\enum\crlc_enums.h %1
copy /y .\service\fsm\include\sm_statemachine.h %1
copy /y .\modem\interface\l4misc\csmcc_atfunc.h %1
copy /y .\modem\interface\rlcmac_struct.h %1
copy /y .\interface\modem\csmss_common_enums.h %1
copy /y .\modem\interface\asn\rr\include\nstd_pkt_meas_report_struct.h %1
copy /y .\modem\interface\l1\fdd\ll1_umts.h %1
copy /y .\modem\gas\common\include\si_context.h %1
copy /y .\modem\uas\common\include\capability.h %1
copy /y .\interface\driver\sys_drv\mmu.h %1
copy /y .\modem\uas\ul2\umac\include\umac_common_enums.h %1
copy /y .\modem\gas\common\include\psi.h %1
copy /y .\modem\interface\asn\rr\include\mtk_csn.h %1
copy /y .\interface\sap\md\urr_msgid.h %1
copy /y .\modem\gas\mac\include\mac_context.h %1
copy /y .\interface\sap\drv\drv_msgid.h %1
