ln -s ./service/kal/include/kal_general_types.h $1/kal_general_types.h
ln -s ./service/kal/include/kal_public_defs.h $1/kal_public_defs.h
ln -s ./service/config/include/stack_config.h $1/stack_config.h
ln -s ./service/kal/include/clib.h $1/clib.h
ln -s ./interface/driver/peripheral/dcl.h $1/dcl.h
ln -s ./service/config/include/hisr_config_internal.h $1/hisr_config_internal.h
ln -s ./service/config/include/app_task_config.h $1/app_task_config.h
ln -s ./service/config/include/hal_task_config.h $1/hal_task_config.h
ln -s ./service/config/include/stack_msgs.h $1/stack_msgs.h
ln -s ./service/kal/include/kal_public_api.h $1/kal_public_api.h
ln -s ./interface/service/tst/kal_trace.h $1/kal_trace.h
ln -s ./driver/drv_def/drv_features_gpio.h $1/drv_features_gpio.h
ln -s ./interface/service/nvram/nvram_defs.h $1/nvram_defs.h
ln -s ./driver/drv_def/drv_features_chip_select.h $1/drv_features_chip_select.h
ln -s ./driver/drv_def/drv_features_6280.h $1/drv_features_6280.h
ln -s ./interface/modem/ps_public_enum.h $1/ps_public_enum.h
ln -s ./driver/sys_drv/regbase/inc/reg_base.h $1/reg_base.h
ln -s ./driver/sys_drv/regbase/inc/reg_base_mt6280.h $1/reg_base_mt6280.h
ln -s ./service/config/include/stack_ltlcom.h $1/stack_ltlcom.h
ln -s ./interface/driver/peripheral/dcl_gpio.h $1/dcl_gpio.h
ln -s ./interface/driver/peripheral/dcl_msdc.h $1/dcl_msdc.h
ln -s ./interface/driver/peripheral/dcl_pmu.h $1/dcl_pmu.h
ln -s ./interface/driver/peripheral/dcl_gpt.h $1/dcl_gpt.h
ln -s ./interface/driver/peripheral/dcl_f32k_clk.h $1/dcl_f32k_clk.h
ln -s ./interface/driver/peripheral/dcl_sim.h $1/dcl_sim.h
ln -s ./interface/driver/peripheral/dcl_adc.h $1/dcl_adc.h
ln -s ./interface/driver/peripheral/dcl_uart.h $1/dcl_uart.h
ln -s ./interface/driver/peripheral/dcl_chr_det.h $1/dcl_chr_det.h
ln -s ./interface/driver/peripheral/dcl_sts.h $1/dcl_sts.h
ln -s ./interface/driver/connectivity/usb_driver/dcl_usb_drv.h $1/dcl_usb_drv.h
ln -s ./interface/driver/peripheral/dcl_bmt.h $1/dcl_bmt.h
ln -s ./interface/driver/peripheral/dcl_pfc.h $1/dcl_pfc.h
ln -s ./interface/driver/peripheral/dcl_pw.h $1/dcl_pw.h
ln -s ./interface/driver/peripheral/dcl_rtc.h $1/dcl_rtc.h
ln -s ./interface/driver/peripheral/dcl_sim_gpio.h $1/dcl_sim_gpio.h
ln -s ./interface/driver/peripheral/dcl_wdt.h $1/dcl_wdt.h
ln -s ./interface/driver/peripheral/DclH_kbd.h $1/DclH_kbd.h
ln -s ./interface/driver/peripheral/DclS_kbd.h $1/DclS_kbd.h
ln -s ./interface/service/nvram/nvram_enums.h $1/nvram_enums.h
ln -s ./interface/modem/ps_public_struct.h $1/ps_public_struct.h
ln -s ./interface/modem/cmux_vp_num.h $1/cmux_vp_num.h
ln -s ./interface/sap/sap_range.h $1/sap_range.h
ln -s ./interface/common/global_def.h $1/global_def.h
ln -s ./service/config/include/stack_buff_pool.h $1/stack_buff_pool.h
ln -s ./custom/service/nvram/custom_nvram_sec.h $1/custom_nvram_sec.h
ln -s ./service/config/include/ctrl_buff_pool.h $1/ctrl_buff_pool.h
ln -s ./driver/drv_def/drv_features_adc.h $1/drv_features_adc.h
ln -s ./interface/sap/module_msg_range.h $1/module_msg_range.h
ln -s ./modem/interface/l4misc/l3_inc_enums.h $1/l3_inc_enums.h
ln -s ./interface/modem/sim_public_enum.h $1/sim_public_enum.h
ln -s ./driver/drv_def/drv_features_rtc.h $1/drv_features_rtc.h
ln -s ./driver/drv_def/drv_features_sim.h $1/drv_features_sim.h
ln -s ./interface/modem/sim_ps_enum.h $1/sim_ps_enum.h
ln -s ./interface/driver/sys_drv/intrCtrl.h $1/intrCtrl.h
ln -s ./driver/sys_drv/cirq/inc/intrCtrl_MT6280.h $1/intrCtrl_MT6280.h
ln -s ./driver/sys_drv/cirq/inc/intrCtrl_MT6280_SW_Handle.h $1/intrCtrl_MT6280_SW_Handle.h
ln -s ./driver/sys_drv/cirq/inc/intrCtrl_SW_Handle.h $1/intrCtrl_SW_Handle.h
ln -s ./interface/modem/l1/fdd/ul1d_rf_cid.h $1/ul1d_rf_cid.h
ln -s ./interface/driver/peripheral/dcl_i2c.h $1/dcl_i2c.h
ln -s ./interface/driver/peripheral/dcl_i2c_owner.h $1/dcl_i2c_owner.h
ln -s ./service/kal/stacklib/include/lcd_ip_cqueue.h $1/lcd_ip_cqueue.h
ln -s ./interface/driver/connectivity/usb_driver/dcl_otg_drv.h $1/dcl_otg_drv.h
ln -s ./interface/driver/connectivity/usb_driver/dcl_usb_hcd.h $1/dcl_usb_hcd.h
ln -s ./interface/driver/peripheral/dcl_aux.h $1/dcl_aux.h
ln -s ./interface/driver/peripheral/dcl_irda.h $1/dcl_irda.h
ln -s ./interface/driver/peripheral/dcl_pwm.h $1/dcl_pwm.h
ln -s ./interface/driver/peripheral/dcl_pxs.h $1/dcl_pxs.h
ln -s ./service/event_info/event_info_utility.h $1/event_info_utility.h
ln -s ./modem/gl1/l1_dm/common/l1_const.h $1/l1_const.h
ln -s ./interface/driver/peripheral/drv_comm.h $1/drv_comm.h
ln -s ./interface/modem/l1/gsm/mph_types.h $1/mph_types.h
ln -s ./interface/service/nvram/nvram_data_items.h $1/nvram_data_items.h
ln -s ./service/config/include/stack_types.h $1/stack_types.h
ln -s ./interface/modem/l1/fdd/ul1d_rf_public.h $1/ul1d_rf_public.h
ln -s ./interface/modem/l1/fdd/ul1_cnst.h $1/ul1_cnst.h
ln -s ./service/config/include/task_config.h $1/task_config.h
ln -s ./interface/sap/svc/sysservice_msgid.h $1/sysservice_msgid.h
ln -s ./service/config/include/kal_user_mem.h $1/kal_user_mem.h
ln -s ./modem/interface/as_common.h $1/as_common.h
ln -s ./interface/sap/md_drv_sap.h $1/md_drv_sap.h
ln -s ./service/config/include/sysconf_statistics.h $1/sysconf_statistics.h
ln -s ./modem/gl1/l1_dm/l1d_ext/l1d_cid.h $1/l1d_cid.h
ln -s ./interface/modem/l1/fdd/ul1_def.h $1/ul1_def.h
ln -s ./service/sst/include/ex_item.h $1/ex_item.h
ln -s ./interface/modem/ps_em_enum.h $1/ps_em_enum.h
ln -s ./interface/modem/em_public_struct.h $1/em_public_struct.h
ln -s ./interface/modem/l1/fdd/ul1cal.h $1/ul1cal.h
ln -s ./service/tst/include/tst.h $1/tst.h
ln -s ./driver/drv_def/drv_features_gpt.h $1/drv_features_gpt.h
ln -s ./driver/drv_def/drv_features_f8f9bc.h $1/drv_features_f8f9bc.h
ln -s ./modem/interface/l4misc/l3_inc_local.h $1/l3_inc_local.h
ln -s ./driver/drv_def/drv_features_wdt.h $1/drv_features_wdt.h
ln -s ./service/kal/include/clib_list.h $1/clib_list.h
ln -s ./driver/drv_def/drv_features_pwm.h $1/drv_features_pwm.h
ln -s ./service/kal/stacklib/include/lcd.h $1/lcd.h
ln -s ./driver/drv_def/drv_features_f32k.h $1/drv_features_f32k.h
ln -s ./driver/drv_def/drv_features_uart.h $1/drv_features_uart.h
ln -s ./driver/drv_def/drv_features_i2c.h $1/drv_features_i2c.h
ln -s ./driver/drv_def/drv_features_gcu.h $1/drv_features_gcu.h
ln -s ./service/nucleus_v2/inc/nucleus.h $1/nucleus.h
ln -s ./driver/drv_def/drv_features.h $1/drv_features.h
ln -s ./driver/drv_def/drv_features_accdet.h $1/drv_features_accdet.h
ln -s ./driver/drv_def/drv_features_bmt.h $1/drv_features_bmt.h
ln -s ./driver/drv_def/drv_features_hif.h $1/drv_features_hif.h
ln -s ./driver/drv_def/drv_features_misc.h $1/drv_features_misc.h
ln -s ./driver/drv_def/drv_features_msdc.h $1/drv_features_msdc.h
ln -s ./driver/drv_def/drv_features_pfc.h $1/drv_features_pfc.h
ln -s ./driver/drv_def/drv_features_spi.h $1/drv_features_spi.h
ln -s ./driver/drv_def/drv_features_usb.h $1/drv_features_usb.h
ln -s ./interface/service/fs/fs_gprot.h $1/fs_gprot.h
ln -s ./modem/interface/l1/inner/l1_types.h $1/l1_types.h
ln -s ./interface/modem/sim_common_enums.h $1/sim_common_enums.h
ln -s ./service/kal/stacklib/include/lcd_lqueue.h $1/lcd_lqueue.h
ln -s ./modem/interface/uas_common_enums.h $1/uas_common_enums.h
ln -s ./modem/interface/l1/inner/l1_core_private.h $1/l1_core_private.h
ln -s ./interface/modem/em_struct.h $1/em_struct.h
ln -s ./modem/gl1/l1_dm/common/tool.h $1/tool.h
ln -s ./interface/modem/sim_public_api.h $1/sim_public_api.h
ln -s ./service/tst/include/L1Trc.h $1/L1Trc.h
ln -s ./interface/driver/sys_drv/cache_sw.h $1/cache_sw.h
ln -s ./interface/modem/sim_ps_api.h $1/sim_ps_api.h
ln -s ./interface/sap/md_sap.h $1/md_sap.h
ln -s ./service/kal/stacklib/include/lcd_cqueue.h $1/lcd_cqueue.h
ln -s ./service/asn1_common/mtkasn_global.h $1/mtkasn_global.h
ln -s ./interface/modem/l1/gsm/l1_types_public.h $1/l1_types_public.h
ln -s ./modem/interface/l1/inner/l1_tool.h $1/l1_tool.h
ln -s ./modem/interface/l1/inner/l1_public.h $1/l1_public.h
ln -s ./modem/interface/l1/gsm/mph_cnst.h $1/mph_cnst.h
ln -s ./service/fs/common/include/fs_internal_def.h $1/fs_internal_def.h
ln -s ./interface/sap/svc_sap.h $1/svc_sap.h
ln -s ./modem/interface/l1/inner/l1_core.h $1/l1_core.h
ln -s ./modem/ul1/ul1_hs_plus/common/ul1_types.h $1/ul1_types.h
ln -s ./service/kal/common/include/stack_timer.h $1/stack_timer.h
ln -s ./service/tst/include/MalmoDriver.h $1/MalmoDriver.h
ln -s ./service/nucleus_v2/inc/tc_defs.h $1/tc_defs.h
ln -s ./service/tst/include/tst_lmu_hw.h $1/tst_lmu_hw.h
ln -s ./service/nucleus_v2/inc/esal_ar_cfg.h $1/esal_ar_cfg.h
ln -s ./service/nucleus_v2/inc/esal_ar_dbg_defs.h $1/esal_ar_dbg_defs.h
ln -s ./service/nucleus_v2/inc/esal_ar_int_defs.h $1/esal_ar_int_defs.h
ln -s ./service/nucleus_v2/inc/esal_ar_isr_defs.h $1/esal_ar_isr_defs.h
ln -s ./service/nucleus_v2/inc/esal_ar_stk_defs.h $1/esal_ar_stk_defs.h
ln -s ./service/nucleus_v2/inc/esal_ar_tmr_defs.h $1/esal_ar_tmr_defs.h
ln -s ./service/nucleus_v2/inc/esal_co_cfg.h $1/esal_co_cfg.h
ln -s ./service/nucleus_v2/inc/esal_dp_cfg.h $1/esal_dp_cfg.h
ln -s ./service/nucleus_v2/inc/esal_extern.h $1/esal_extern.h
ln -s ./service/nucleus_v2/inc/esal_ge_cfg.h $1/esal_ge_cfg.h
ln -s ./service/nucleus_v2/inc/esal_ge_com_defs.h $1/esal_ge_com_defs.h
ln -s ./service/nucleus_v2/inc/esal_ge_dbg_defs.h $1/esal_ge_dbg_defs.h
ln -s ./service/nucleus_v2/inc/esal_ge_int_defs.h $1/esal_ge_int_defs.h
ln -s ./service/nucleus_v2/inc/esal_ge_isr_defs.h $1/esal_ge_isr_defs.h
ln -s ./service/nucleus_v2/inc/esal_ge_mem_defs.h $1/esal_ge_mem_defs.h
ln -s ./service/nucleus_v2/inc/esal_ge_rte_defs.h $1/esal_ge_rte_defs.h
ln -s ./service/nucleus_v2/inc/esal_ge_stk_defs.h $1/esal_ge_stk_defs.h
ln -s ./service/nucleus_v2/inc/esal_ge_tmr_defs.h $1/esal_ge_tmr_defs.h
ln -s ./service/nucleus_v2/inc/esal_pr_cfg.h $1/esal_pr_cfg.h
ln -s ./service/nucleus_v2/inc/esal_pr_tmr_defs.h $1/esal_pr_tmr_defs.h
ln -s ./service/nucleus_v2/inc/esal_ts_cfg.h $1/esal_ts_cfg.h
ln -s ./service/nucleus_v2/inc/esal_ts_rte_defs.h $1/esal_ts_rte_defs.h
ln -s ./service/nucleus_v2/inc/esal_ts_stk_defs.h $1/esal_ts_stk_defs.h
ln -s ./interface/modem/flc2_config.h $1/flc2_config.h
ln -s ./custom/modem/ul1_rf/MT6280RF_UMTS_FDD/ul1d_custom_rf.h $1/ul1d_custom_rf.h
ln -s ./interface/modem/l1/fdd/ul1d_rf_common.h $1/ul1d_rf_common.h
ln -s ./service/nucleus_v2/inc/cs_defs.h $1/cs_defs.h
ln -s ./service/tst/include/L1Trc_lmu.h $1/L1Trc_lmu.h
ln -s ./modem/interface/uas_gas_enums.h $1/uas_gas_enums.h
ln -s ./service/nucleus_v2/inc/pm_defs.h $1/pm_defs.h
ln -s ./service/nucleus_v2/inc/tm_defs.h $1/tm_defs.h
ln -s ./service/nucleus_v2/inc/ev_defs.h $1/ev_defs.h
ln -s ./service/nucleus_v2/inc/qu_defs.h $1/qu_defs.h
ln -s ./service/nucleus_v2/inc/sm_defs.h $1/sm_defs.h
ln -s ./service/nucleus_v2/inc/dm_defs.h $1/dm_defs.h
ln -s ./service/nucleus_v2/inc/er_extr.h $1/er_extr.h
ln -s ./service/nucleus_v2/inc/mb_defs.h $1/mb_defs.h
ln -s ./service/nucleus_v2/inc/pi_defs.h $1/pi_defs.h
ln -s ./service/nucleus_v2/inc/plus_cfg.h $1/plus_cfg.h
ln -s ./service/nucleus_v2/inc/zc_extr.h $1/zc_extr.h
ln -s ./modem/interface/l1/inner/l1_private.h $1/l1_private.h
ln -s ./service/fsm/include/sm_type.h $1/sm_type.h
ln -s ./driver/sleep_drv/inc/dcxo_div.h $1/dcxo_div.h
ln -s ./modem/interface/divider_public.h $1/divider_public.h
ln -s ./modem/interface/l1/inner/l1_timertype.h $1/l1_timertype.h
ln -s ./modem/uas/interface/local_inc/uas_common_struct.h $1/uas_common_struct.h
ln -s ./interface/driver/peripheral/adc_cali.h $1/adc_cali.h
ln -s ./interface/modem/l1/fdd/ul1_struct.h $1/ul1_struct.h
ln -s ./modem/ul1/ul1_hs_plus/ul1d/ul1d_cid.h $1/ul1d_cid.h
ln -s ./interface/service/fs/fs_type.h $1/fs_type.h
ln -s ./modem/interface/l3llc_enums.h $1/l3llc_enums.h
ln -s ./modem/gas/common/include/rr_common_def.h $1/rr_common_def.h
ln -s ./modem/gas/common/include/rr_mpal_interface.h $1/rr_mpal_interface.h
ln -s ./modem/interface/asn/rr/include/csn_common.h $1/csn_common.h
ln -s ./interface/modem/device.h $1/device.h
ln -s ./interface/modem/l1/gsm/l1_interface.h $1/l1_interface.h
ln -s ./modem/interface/asn/rr/include/gprs_rlcmac_common_struct.h $1/gprs_rlcmac_common_struct.h
ln -s ./modem/interface/rlc_mac_enums.h $1/rlc_mac_enums.h
ln -s ./interface/modem/tcm_api.h $1/tcm_api.h
ln -s ./modem/gas/common/include/rr_context.h $1/rr_context.h
ln -s ./service/kal/stacklib/include/stacklib.h $1/stacklib.h
ln -s ./modem/interface/rr2mpal_struct.h $1/rr2mpal_struct.h
ln -s ./service/asn1_common/asn_memory.h $1/asn_memory.h
ln -s ./modem/interface/l1/inner/ul1_timertype.h $1/ul1_timertype.h
ln -s ./custom/modem/common/ps/ul1_nvram_def.h $1/ul1_nvram_def.h
ln -s ./service/asn1_common/asn_common.h $1/asn_common.h
ln -s ./service/kal/common/include/kal_debug.h $1/kal_debug.h
ln -s ./service/kal/mlib/include/mlib_dll.h $1/mlib_dll.h
ln -s ./modem/interface/asn/rr/include/gprs_rlcmac_dl_struct.h $1/gprs_rlcmac_dl_struct.h
ln -s ./interface/modem/l4c_msg_hdlr_defs.h $1/l4c_msg_hdlr_defs.h
ln -s ./service/kal/common/include/event_shed.h $1/event_shed.h
ln -s ./interface/sap/md/l4_msgid.h $1/l4_msgid.h
ln -s ./modem/gas/common/include/psi_si_common.h $1/psi_si_common.h
ln -s ./interface/service/nvram/nvram_editor_data_item.h $1/nvram_editor_data_item.h
ln -s ./service/nucleus_v2/inc/tm_extr.h $1/tm_extr.h
ln -s ./modem/gas/common/include/si.h $1/si.h
ln -s ./interface/modem/smu_common_enums.h $1/smu_common_enums.h
ln -s ./modem/common/mcd/include/mcd_struct.h $1/mcd_struct.h
ln -s ./interface/modem/flc2_ent_functions.h $1/flc2_ent_functions.h
ln -s ./service/kal/stacklib/include/dlist.h $1/dlist.h
ln -s ./modem/interface/l4misc/l4c_common_enum.h $1/l4c_common_enum.h
ln -s ./service/config/include/hisr_config.h $1/hisr_config.h
ln -s ./modem/interface/l1/inner/ul1_public.h $1/ul1_public.h
ln -s ./modem/interface/mcd/include/mcd.h $1/mcd.h
ln -s ./modem/interface/l1/inner/ul1_option.h $1/ul1_option.h
ln -s ./modem/interface/asn/rr/include/gprs_rlcmac_ul_struct.h $1/gprs_rlcmac_ul_struct.h
ln -s ./driver/sys_drv/pdn/inc/pdn_def.h $1/pdn_def.h
ln -s ./service/kal/common/include/kal_debug_common_defs.h $1/kal_debug_common_defs.h
ln -s ./service/kal/common/include/kal_error_code.h $1/kal_error_code.h
ln -s ./service/kal/common/include/kal_internal_api.h $1/kal_internal_api.h
ln -s ./service/kal/nucleus/include/kal_debug_nucleus.h $1/kal_debug_nucleus.h
ln -s ./service/kal/nucleus/include/kal_nucleus.h $1/kal_nucleus.h
ln -s ./service/kal/nucleus/include/kal_nucleus_common_defs.h $1/kal_nucleus_common_defs.h
ln -s ./service/config/include/syscomp_config.h $1/syscomp_config.h
ln -s ./driver/drv_def/drv_features_mmsysmisc.h $1/drv_features_mmsysmisc.h
ln -s ./interface/driver/drv_sw_def/drv_sw_features_mmsysmisc.h $1/drv_sw_features_mmsysmisc.h
ln -s ./interface/modem/sim_public_struct.h $1/sim_public_struct.h
ln -s ./driver/sys_drv/pdn/inc/pdn_hw_mt6280_series.h $1/pdn_hw_mt6280_series.h
ln -s ./driver/sys_drv/pdn/inc/pdn_hw_series.h $1/pdn_hw_series.h
ln -s ./modem/interface/asn/rr/include/rmc_peer_dl_struct.h $1/rmc_peer_dl_struct.h
ln -s ./service/fsm/include/sm_event.h $1/sm_event.h
ln -s ./modem/gas/rrm/rmc/include/meas_context.h $1/meas_context.h
ln -s ./driver/sys_drv/pdn/inc/drvpdn.h $1/drvpdn.h
ln -s ./driver/sys_drv/pdn/inc/pdn_def_mt6280_series.h $1/pdn_def_mt6280_series.h
ln -s ./modem/common/mcd/include/mcd_enum.h $1/mcd_enum.h
ln -s ./modem/gas/rrm/common/include/rrm_context.h $1/rrm_context.h
ln -s ./interface/middleware/meta/ul1tst_msg.h $1/ul1tst_msg.h
ln -s ./interface/modem/mmi_l3_enums.h $1/mmi_l3_enums.h
ln -s ./modem/interface/asn/rr/include/error_struct_enum.h $1/error_struct_enum.h
ln -s ./interface/modem/sim_ps_struct.h $1/sim_ps_struct.h
ln -s ./service/sys_svc/gfh/public/br_GFH.h $1/br_GFH.h
ln -s ./modem/interface/uas_gas_struct.h $1/uas_gas_struct.h
ln -s ./modem/interface/as2nas_struct.h $1/as2nas_struct.h
ln -s ./modem/interface/l4misc/l4c2phb_enums.h $1/l4c2phb_enums.h
ln -s ./modem/gas/common/include/rr_data_ind.h $1/rr_data_ind.h
ln -s ./modem/uas/ul2/common/include/rlc_cid.h $1/rlc_cid.h
ln -s ./modem/interface/asn/rr/include/mtkcsn_global.h $1/mtkcsn_global.h
ln -s ./driver/sys_drv/init/inc/init.h $1/init.h
ln -s ./interface/service/sys_svc/init_public.h $1/init_public.h
ln -s ./modem/interface/l1/gsm/mph_cs_def.h $1/mph_cs_def.h
ln -s ./modem/gas/common/include/rr_common_headers.h $1/rr_common_headers.h
ln -s ./modem/interface/asn/asn1lib/include/asn1lib.h $1/asn1lib.h
ln -s ./modem/uas/ul2/common/include/ul2_common_def.h $1/ul2_common_def.h
ln -s ./modem/uas/interface/enum/cmac_enums.h $1/cmac_enums.h
ln -s ./modem/uas/interface/enum/crlc_enums.h $1/crlc_enums.h
ln -s ./service/fsm/include/sm_statemachine.h $1/sm_statemachine.h
ln -s ./modem/interface/l4misc/csmcc_atfunc.h $1/csmcc_atfunc.h
ln -s ./modem/interface/rlcmac_struct.h $1/rlcmac_struct.h
ln -s ./interface/modem/csmss_common_enums.h $1/csmss_common_enums.h
ln -s ./modem/interface/asn/rr/include/nstd_pkt_meas_report_struct.h $1/nstd_pkt_meas_report_struct.h
ln -s ./modem/interface/l1/fdd/ll1_umts.h $1/ll1_umts.h
ln -s ./modem/gas/common/include/si_context.h $1/si_context.h
ln -s ./modem/uas/common/include/capability.h $1/capability.h
ln -s ./interface/driver/sys_drv/mmu.h $1/mmu.h
ln -s ./modem/uas/ul2/umac/include/umac_common_enums.h $1/umac_common_enums.h
ln -s ./modem/gas/common/include/psi.h $1/psi.h
ln -s ./modem/interface/asn/rr/include/mtk_csn.h $1/mtk_csn.h
ln -s ./interface/sap/md/urr_msgid.h $1/urr_msgid.h
ln -s ./modem/gas/mac/include/mac_context.h $1/mac_context.h
ln -s ./interface/sap/drv/drv_msgid.h $1/drv_msgid.h
